<!DOCTYPE html>
<!-- saved from url=(0022)http://localhost:3849/ -->
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">


<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Adam Abdullatif Hussein">

<title>Unit4_RTutorial Week</title>
<style class="anchorjs"></style><style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="./Unit4_RTutorial Week_files/clipboard.min.js.download"></script><style type="text/css" id="operaUserStyle"></style>
<script src="./Unit4_RTutorial Week_files/quarto.js.download"></script>
<script src="./Unit4_RTutorial Week_files/popper.min.js.download"></script>
<script src="./Unit4_RTutorial Week_files/tippy.umd.min.js.download"></script>
<script src="./Unit4_RTutorial Week_files/anchor.min.js.download"></script>
<link href="./Unit4_RTutorial Week_files/tippy.css" rel="stylesheet">
<link href="./Unit4_RTutorial Week_files/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="./Unit4_RTutorial Week_files/bootstrap.min.js.download"></script>
<link href="./Unit4_RTutorial Week_files/bootstrap-icons.css" rel="stylesheet">
<link href="./Unit4_RTutorial Week_files/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


<style type="text/css"></style></head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Unit4_RTutorial Week</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Adam Abdullatif Hussein </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In Unit 4: You will discover text and social network analysis by reviewing the walkthroughs from the <a href="https://datascienceineducation.com/">Data science in education Using R</a> book. In Unit3, we examined the foundations of the collaborative data-intensive improvement (CDI) model and discussed the text mining methods in education from a theoretical perspective. Now, you will able to practice text-mining in the Walkthrough 5: Text Analysis with Twitter Data. After you completed the Walkthrough 5, you will move to the Social Network Analysis part. In the Walkthrough 6, you will discover interactions among the Twitter users by following SNA. To complete this week’s tutorial, please read through everything carefully and complete all “Your Turn” parts. Each “Your Turn” is 1 point and render&amp;publishing your work (e.g., RPubs, QuartoPubs, GitHub) is 1 point.</p>
<section id="walkthrough-5-text-analysis-with-social-media-data" class="level2">
<h2 class="anchored" data-anchor-id="walkthrough-5-text-analysis-with-social-media-data">Walkthrough 5: Text Analysis With Social Media Data<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#walkthrough-5-text-analysis-with-social-media-data" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h2>
<section id="topics-emphasized" class="level3">
<h3 class="anchored" data-anchor-id="topics-emphasized">Topics Emphasized<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#topics-emphasized" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<ul>
<li><p>Tidying data</p></li>
<li><p>Transforming data</p></li>
<li><p>Visualizing data</p></li>
</ul>
</section>
<section id="functions-introduced" class="level3">
<h3 class="anchored" data-anchor-id="functions-introduced">Functions Introduced<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#functions-introduced" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<ul>
<li><p><code>sample_n()</code></p></li>
<li><p><code>set.seed()</code></p></li>
<li><p><code>tidytext::unnest_tokens()</code></p></li>
<li><p><code>nrc::get_sentiments()</code></p></li>
<li><p><code>tidytext::inner_join()</code></p></li>
</ul>
</section>
<section id="vocabulary" class="level3">
<h3 class="anchored" data-anchor-id="vocabulary">Vocabulary<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#vocabulary" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<ul>
<li><p>RDS files</p></li>
<li><p>text analysis</p></li>
<li><p>stop words</p></li>
<li><p>tokenize</p></li>
</ul>
</section>
</section>
<section id="chapter-overview" class="level2">
<h2 class="anchored" data-anchor-id="chapter-overview">Chapter Overview<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#chapter-overview" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h2>
<p>In this chapter, we focus on analyzing textual data from Twitter. We focus on this particular data&nbsp;source because we think it is relevant to a number of educational topics and questions, including how newcomers learn to visualize data. In addition, Twitter data is complex, and includes not only information about who posted a tweet (and when - and a great deal of additional information (see&nbsp;(<a href="https://datascienceineducation.com/references#ref-R-rtweet">Michael W. Kearney et al., 2022</a>)), it also includes the text of the tweet). This makes it especially well-suited for exploring the uses of text analysis, which is broadly part of a group of techniques involving the analysis of text as data, Natural Language Processing (often abbreviated NLP)&nbsp;(<a href="https://datascienceineducation.com/references#ref-hirschberg2015">Hirschberg &amp; Manning, 2015</a>).</p>
<section id="background" class="level3">
<h3 class="anchored" data-anchor-id="background">Background<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#background" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p>When we think about data science in education, our minds tends to go data stored in spreadsheets. But what can we learn about the student experience from text data? Take a moment to mentally review all the moments in your work day that you generated or consumed text data. In education, we’re surrounded by it. We do our lessons in word processor documents, our students submit assignments online, and the school community expresses themselves on public social media platforms. The text we generate can be an authentic reflection of reality in schools, so how might we learn from it?</p>
<p>Even the most basic text analysis techniques will expand your data science toolkit. For example, you can use text analysis to count the number of key words that appear in open ended survey responses. You can analyze word patterns in student responses or message board posts.</p>
<p>Analyzing a collection of text is different from analyzing large numerical datasets because words don’t have agreed upon values the way numbers do. The number 2 will always be more than 1 and less than 3. The word “fantastic,” on the other hand, has multiple ambiguous levels of degree depending on interpretation and context.</p>
<p>Using text analysis can help to broadly estimate what is happening in the text. When paired with observations, interviews, and close review of the text, this approach can help education staff learn from text data. In this chapter, we’ll learn how to count the frequency of words in a dataset and associate those words with common feelings like positivity or joy.</p>
<p>We’ll show these techniques using a dataset of tweets. We encourage you to complete the walkthrough, then reflect on how the skills learned can be applied to other texts, like word processing documents or websites.</p>
</section>
<section id="data-source" class="level3">
<h3 class="anchored" data-anchor-id="data-source">Data Source<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#data-source" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p>It’s useful to learn text analysis techniques from datasets that are available for download. Take a moment to do an online search for “download tweet dataset” and note the abundance of Twitter datasets available. Since there’s so much, it’s useful to narrow the tweets to only those that help you answer your analytic questions. Hashtags are text within a tweet that act as a way to categorize content. Here’s an example:</p>
<blockquote class="blockquote">
<p>RT @CKVanPay: I’m trying to recreate some Stata code in R, anyone have a good resource for what certain functions in Stata are doing? #RStats #Stata</p>
</blockquote>
<p>Twitter recognizes any words that start with a “#” as a hashtag. The hashtags “#RStats” and “#Stata” make this tweet conveniently searchable. If Twitter uses search for “#RStats”, Twitter returns all the Tweets containing that hashtag.</p>
<p>In this example, we’ll be analyzing a dataset of tweets that have the hashtag #tidytuesday (<a href="https://twitter.com/hashtag/tidytuesday" class="uri">https://twitter.com/hashtag/tidytuesday</a>). #tidytuesday is a community sparked by the work of one of the&nbsp;<em>Data Science in Education Using R</em>&nbsp;co-authors, Jesse Mostipak, who created the (related) #r4ds community from which #tidytuesday was created. #tidytuesday is a weekly data visualization challenge. A great place to see examples from past #tidytuesday challenges is an interactive Shiny application (<a href="https://github.com/nsgrantham/tidytuesdayrocks" class="uri">https://github.com/nsgrantham/tidytuesdayrocks</a>).</p>
<p>The #tidytuesday hashtag (search Twitter for the hashtag, or see the results here:&nbsp;<a href="http://bit.ly/tidytuesday-search" class="uri">http://bit.ly/tidytuesday-search</a>) returns tweets about the weekly TidyTuesday practice, where folks learning R create and tweet data visualizations they made while learning to use tidyverse R packages.</p>
</section>
<section id="methods" class="level3">
<h3 class="anchored" data-anchor-id="methods">Methods<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#methods" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p>In this walkthrough, we’ll be learning how to count words in a text dataset. We’ll also use a technique called sentiment analysis to count and visualize the appearance of words that have a positive association. Lastly, we’ll learn how to get more context by selecting random rows of tweets for closer reading.</p>
</section>
</section>
<section id="load-packages" class="level2">
<h2 class="anchored" data-anchor-id="load-packages">Load Packages<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#load-packages" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h2>
<p>For this analysis, we’ll be using the {tidyverse}, {here}, and {dataedu} packages. We will also use the {tidytext} package for working with textual data&nbsp;(<a href="https://datascienceineducation.com/references#ref-R-tidytext">Robinson &amp; Silge, 2022</a>). As it has not been used previously in the book, you may need to install the {tidytext} package (and - if you haven’t just yet - the other packages), first. For instructions on and an overview about installing packages, see the&nbsp;<a href="https://datascienceineducation.com/c06#c06p">Packages section</a>&nbsp;of the&nbsp;<a href="https://datascienceineducation.com/c06#c06">Foundational Skills</a>chapter.</p>
<p>Let’s load our packages before moving on to import the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="http://localhost:3849/#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="http://localhost:3849/#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'here' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at C:/Users/thead/AppData/Local/Temp/Rar$DIa22568.32651</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="http://localhost:3849/#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidytext)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidytext' was built under R version 4.3.2</code></pre>
</div>
</div>
<p>We will <strong>load dataedu library</strong> as well. But, before loading that library, we need to install the library. In your previous assignment, you practiced to install a library from CRAN repository. Yet, that is not only the way to install a library. Sometimes, developer creates new libraries and share them through the GitHub. This is also a case for the “dataedu” library. Check the code below and run it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="http://localhost:3849/#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install remotes</span></span>
<span id="cb8-2"><a href="http://localhost:3849/#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"remotes"</span>, <span class="at">repos =</span> <span class="st">"http://cran.us.r-project.org"</span>)</span>
<span id="cb8-3"><a href="http://localhost:3849/#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="http://localhost:3849/#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># install the dataedu package</span></span>
<span id="cb8-5"><a href="http://localhost:3849/#cb8-5" aria-hidden="true" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">"data-edu/dataedu"</span>)</span>
<span id="cb8-6"><a href="http://localhost:3849/#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="http://localhost:3849/#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co">#load the library</span></span>
<span id="cb8-8"><a href="http://localhost:3849/#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dataedu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="import-data" class="level2">
<h2 class="anchored" data-anchor-id="import-data">Import Data<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#import-data" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h2>
<p>We’ve included the raw dataset of TidyTuesday tweets in the {dataedu} package. You can see the dataset by typing&nbsp;<code>tt_tweets</code>. Let’s start by assigning the name&nbsp;<code>raw_tweets</code>&nbsp;to this dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="http://localhost:3849/#cb9-1" aria-hidden="true" tabindex="-1"></a>raw_tweets <span class="ot">&lt;-</span> dataedu<span class="sc">::</span>tt_tweets</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="your-turn" class="level3">
<h3 class="anchored" data-anchor-id="your-turn">Your Turn:<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#your-turn" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p>Let’s return to our&nbsp;<code>raw_tweets</code>&nbsp;dataset. Run&nbsp;<code>str(raw_tweets)</code>&nbsp;and notice the number of variables in this dataset. It’s good practice to use functions like&nbsp;<code>glimpse()</code>&nbsp;, <code>head()</code>&nbsp;or&nbsp;<code>str()</code>&nbsp;to look at the data type of each variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="http://localhost:3849/#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(raw_tweets)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 4,418
Columns: 90
$ user_id                 &lt;chr&gt; "1159211379963772928", "1073323083170238466", …
$ status_id               &lt;chr&gt; "1163154266065735680", "1163247504542130176", …
$ created_at              &lt;dttm&gt; 2019-08-18 18:22:42, 2019-08-19 00:33:11, 201…
$ screen_name             &lt;chr&gt; "MKumarYYC", "cizzart", "cizzart", "cizzart", …
$ text                    &lt;chr&gt; "First #TidyTuesday submission! Roman emperors…
$ source                  &lt;chr&gt; "Twitter Web App", "Twitter Web App", "Twitter…
$ display_text_width      &lt;dbl&gt; 178, 280, 196, 214, 262, 227, 260, 271, 117, 2…
$ reply_to_status_id      &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ reply_to_user_id        &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ reply_to_screen_name    &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ is_quote                &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALS…
$ is_retweet              &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALS…
$ favorite_count          &lt;int&gt; 9, 1, 1, 1, 0, 1, 1, 1, 6, 5, 1, 4, 1, 1, 2, 1…
$ retweet_count           &lt;int&gt; 3, 1, 0, 1, 1, 1, 1, 0, 3, 2, 0, 2, 1, 1, 0, 1…
$ quote_count             &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ reply_count             &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ hashtags                &lt;list&gt; &lt;"TidyTuesday", "rstats", "DataScience"&gt;, &lt;"M…
$ symbols                 &lt;list&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ urls_url                &lt;list&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ urls_t.co               &lt;list&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ urls_expanded_url       &lt;list&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ media_url               &lt;list&gt; "http://pbs.twimg.com/media/ECRao8OU8AAFVux.p…
$ media_t.co              &lt;list&gt; "https://t.co/1LTWIUBXwA", "https://t.co/Bhqv…
$ media_expanded_url      &lt;list&gt; "https://twitter.com/MKumarYYC/status/1163154…
$ media_type              &lt;list&gt; "photo", "photo", "photo", "photo", "photo", …
$ ext_media_url           &lt;list&gt; "http://pbs.twimg.com/media/ECRao8OU8AAFVux.p…
$ ext_media_t.co          &lt;list&gt; "https://t.co/1LTWIUBXwA", "https://t.co/Bhqv…
$ ext_media_expanded_url  &lt;list&gt; "https://twitter.com/MKumarYYC/status/1163154…
$ ext_media_type          &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ mentions_user_id        &lt;list&gt; NA, "2792557771", "4471336875", "2249583145",…
$ mentions_screen_name    &lt;list&gt; NA, "eldestapeweb", "INDECArgentina", "ENACOM…
$ lang                    &lt;chr&gt; "en", "es", "es", "es", "es", "es", "es", "es"…
$ quoted_status_id        &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ quoted_text             &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ quoted_created_at       &lt;dttm&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ quoted_source           &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ quoted_favorite_count   &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ quoted_retweet_count    &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ quoted_user_id          &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ quoted_screen_name      &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ quoted_name             &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ quoted_followers_count  &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ quoted_friends_count    &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ quoted_statuses_count   &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ quoted_location         &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ quoted_description      &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ quoted_verified         &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ retweet_status_id       &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ retweet_text            &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ retweet_created_at      &lt;dttm&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ retweet_source          &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ retweet_favorite_count  &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ retweet_retweet_count   &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ retweet_user_id         &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ retweet_screen_name     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ retweet_name            &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ retweet_followers_count &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ retweet_friends_count   &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ retweet_statuses_count  &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ retweet_location        &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ retweet_description     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ retweet_verified        &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ place_url               &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ place_name              &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ place_full_name         &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ place_type              &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ country                 &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ country_code            &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ geo_coords              &lt;list&gt; &lt;NA, NA&gt;, &lt;NA, NA&gt;, &lt;NA, NA&gt;, &lt;NA, NA&gt;, &lt;NA, …
$ coords_coords           &lt;list&gt; &lt;NA, NA&gt;, &lt;NA, NA&gt;, &lt;NA, NA&gt;, &lt;NA, NA&gt;, &lt;NA, …
$ bbox_coords             &lt;list&gt; &lt;NA, NA, NA, NA, NA, NA, NA, NA&gt;, &lt;NA, NA, NA…
$ status_url              &lt;chr&gt; "https://twitter.com/MKumarYYC/status/11631542…
$ name                    &lt;chr&gt; "Mehul Kumar", "César", "César", "César", "Cés…
$ location                &lt;chr&gt; "Calgary, AB", "Posadas, Argentina", "Posadas,…
$ description             &lt;chr&gt; "Dabbling in data devices | #rstats/#datascien…
$ url                     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ protected               &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALS…
$ followers_count         &lt;int&gt; 10, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57…
$ friends_count           &lt;int&gt; 21, 120, 120, 120, 120, 120, 120, 120, 120, 12…
$ listed_count            &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ statuses_count          &lt;int&gt; 18, 152, 152, 152, 152, 152, 152, 152, 152, 15…
$ favourites_count        &lt;int&gt; 180, 977, 977, 977, 977, 977, 977, 977, 977, 9…
$ account_created_at      &lt;dttm&gt; 2019-08-07 21:15:04, 2018-12-13 21:05:39, 201…
$ verified                &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALS…
$ profile_url             &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ profile_expanded_url    &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ account_lang            &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ profile_banner_url      &lt;chr&gt; "https://pbs.twimg.com/profile_banners/1159211…
$ profile_background_url  &lt;chr&gt; NA, "http://abs.twimg.com/images/themes/theme1…
$ profile_image_url       &lt;chr&gt; "http://pbs.twimg.com/profile_images/116315617…</code></pre>
</div>
</div>
<p><strong>What did you realize about this data?</strong></p>
<ul>
<li><strong>The data set seems incredibly thorough…</strong></li>
<li>There is location data which could potentially be dangerous to expose.</li>
</ul>
<p>For this walkthrough, we won’t need all 90 variables so let’s clean the dataset and keep only the ones we want.</p>
</section>
</section>
<section id="process-data" class="level2">
<h2 class="anchored" data-anchor-id="process-data">Process Data<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#process-data" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h2>
<p>In this section we’ll select the columns we need for our analysis and we’ll transform the dataset so each row represents a word. After that, our dataset will be ready for exploring.</p>
<section id="your-turn-1" class="level3">
<h3 class="anchored" data-anchor-id="your-turn-1">Your Turn:<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#your-turn-1" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p>Complete the code below.</p>
<p>First, let’s use&nbsp;<code>select()</code>&nbsp;to pick the two columns we’ll need:&nbsp;<code>status_id</code>&nbsp;and&nbsp;<code>text</code>.</p>
<p><code>status_id</code>&nbsp;will help us associate interesting words with a particular tweet and&nbsp;<code>text</code>&nbsp;will give us the text from that tweet.</p>
<p>We’ll also change&nbsp;<code>status_id</code>&nbsp;to the character data type since it’s meant to label tweets and doesn’t actually represent a numerical value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="http://localhost:3849/#cb12-1" aria-hidden="true" tabindex="-1"></a>tweets <span class="ot">&lt;-</span></span>
<span id="cb12-2"><a href="http://localhost:3849/#cb12-2" aria-hidden="true" tabindex="-1"></a>  raw_tweets <span class="sc">|&gt;</span></span>
<span id="cb12-3"><a href="http://localhost:3849/#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#filter for English tweets</span></span>
<span id="cb12-4"><a href="http://localhost:3849/#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(lang <span class="sc">==</span> <span class="st">"en"</span>) <span class="sc">|&gt;</span></span>
<span id="cb12-5"><a href="http://localhost:3849/#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(status_id,text) <span class="sc">|&gt;</span></span>
<span id="cb12-6"><a href="http://localhost:3849/#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Convert the ID field to the character data type</span></span>
<span id="cb12-7"><a href="http://localhost:3849/#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">status_id =</span> <span class="fu">as.character</span>(status_id))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now the dataset has a column to identify each tweet and a column that shows the text that users tweeted. But each row has the entire tweet in the&nbsp;<code>text</code>&nbsp;variable, which makes it hard to analyze. If we kept our dataset like this, we’d need to use functions on each row to do something like count the number of times the word “good” appears. We can count words more efficiently if each row represented a single word. Splitting sentences in a row into single words in a row is called “tokenizing.” In their book&nbsp;<em>Text Mining With R</em>,&nbsp;Silge &amp; Robinson (<a href="https://datascienceineducation.com/references#ref-silge2017text">2017</a>)describe tokens this way:</p>
<blockquote class="blockquote">
<p>A token is a meaningful unit of text, such as a word, that we are interested in using for analysis, and tokenization is the process of splitting text into tokens. This one-token-per-row structure is in contrast to the ways text is often stored in current analyses, perhaps as strings or in a document-term matrix.</p>
</blockquote>
<p>Let’s use&nbsp;<code>unnest_tokens()</code>&nbsp;from the {tidytext} package to take our dataset of tweets and transform it into a dataset of words.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="http://localhost:3849/#cb13-1" aria-hidden="true" tabindex="-1"></a>tokens <span class="ot">&lt;-</span> </span>
<span id="cb13-2"><a href="http://localhost:3849/#cb13-2" aria-hidden="true" tabindex="-1"></a>  tweets <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="http://localhost:3849/#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest_tokens</span>(<span class="at">output =</span> word, <span class="at">input =</span> text)</span>
<span id="cb13-4"><a href="http://localhost:3849/#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="http://localhost:3849/#cb13-5" aria-hidden="true" tabindex="-1"></a>tokens </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 131,232 × 2
   status_id           word       
   &lt;chr&gt;               &lt;chr&gt;      
 1 1163154266065735680 first      
 2 1163154266065735680 tidytuesday
 3 1163154266065735680 submission 
 4 1163154266065735680 roman      
 5 1163154266065735680 emperors   
 6 1163154266065735680 and        
 7 1163154266065735680 their      
 8 1163154266065735680 rise       
 9 1163154266065735680 to         
10 1163154266065735680 power      
# ℹ 131,222 more rows</code></pre>
</div>
</div>
<p>We use&nbsp;<code>output = word</code>&nbsp;to tell&nbsp;<code>unnest_tokens()</code>&nbsp;that we want our column of tokens to be called&nbsp;<code>word</code>. We use&nbsp;<code>input = text</code>&nbsp;to tell&nbsp;<code>unnest_tokens()</code>&nbsp;to tokenize the tweets in the&nbsp;<code>text</code>&nbsp;column of our&nbsp;<code>tweets</code>&nbsp;dataset. The result is a new dataset where each row has a single word in the&nbsp;<code>word</code>&nbsp;column and a unique ID in the&nbsp;<code>status_id</code>&nbsp;column that tells us which tweet the word appears in.</p>
</section>
<section id="your-turn-2" class="level3">
<h3 class="anchored" data-anchor-id="your-turn-2">Your Turn:<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#your-turn-2" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p><strong>What happened after you tokenized the data? How did the number of observations change?</strong></p>
<ul>
<li>The number of observations increased over 30 times.</li>
</ul>
</section>
<section id="removing-stop-words" class="level3">
<h3 class="anchored" data-anchor-id="removing-stop-words">Removing Stop Words<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#removing-stop-words" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p>We’re almost ready to start analyzing the dataset! There’s one more step we’ll take–removing common words that don’t help us learn about what people are tweeting about. Words like “the” or “a” are in a category of words called “stop words”. Stop words serve a function in verbal communication, but don’t tell us much on their own. As a result, they clutter our dataset of useful words and make it harder to manage the volume of words we want to analyze. The {tidytext} package includes a dataset called&nbsp;<code>stop_words</code>&nbsp;that we’ll use to remove rows containing stop words. We’ll use&nbsp;<code>anti_join</code>() on our&nbsp;<code>tokens</code>&nbsp;dataset and the&nbsp;<code>stop_words</code>dataset to keep only rows that have words&nbsp;<em>not</em>&nbsp;appearing in the&nbsp;<code>stop_words</code>&nbsp;dataset.</p>
<p>Run the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="http://localhost:3849/#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(stop_words)</span>
<span id="cb15-2"><a href="http://localhost:3849/#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="http://localhost:3849/#cb15-3" aria-hidden="true" tabindex="-1"></a>tokens <span class="ot">&lt;-</span></span>
<span id="cb15-4"><a href="http://localhost:3849/#cb15-4" aria-hidden="true" tabindex="-1"></a>  tokens <span class="sc">%&gt;%</span></span>
<span id="cb15-5"><a href="http://localhost:3849/#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(stop_words, <span class="at">by =</span> <span class="st">"word"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Why does this work? Let’s look closer.&nbsp;<code>inner_join()</code>&nbsp;matches the observations in one dataset to another by a specified common variable. Any rows that don’t have a match get dropped from the resulting dataset.&nbsp;<code>anti_join()</code>&nbsp;does the same thing as&nbsp;<code>inner_join()</code>&nbsp;except it drops matching rows and keeps the rows that&nbsp;<em>don’t</em>&nbsp;match. This is convenient for our analysis because we want to remove rows from&nbsp;<code>tokens</code>&nbsp;that contain words in the&nbsp;<code>stop_words</code>&nbsp;dataset. When we call&nbsp;<code>anti_join()</code>, we’re left with rows that&nbsp;<em>don’t</em>match words in the&nbsp;<code>stop_words</code>&nbsp;dataset. These remaining words are the ones we’ll be analyzing.</p>
<p>One final note before we start counting words: Remember when we first tokenized our dataset and we passed&nbsp;<code>unnest_tokens()</code>&nbsp;the argument&nbsp;<code>output = word</code>? We conveniently chose&nbsp;<code>word</code>&nbsp;as our column name because it matches the column name&nbsp;<code>word</code>&nbsp;in the&nbsp;<code>stop_words</code>&nbsp;dataset. This makes our call to&nbsp;<code>anti_join()</code>&nbsp;simpler because&nbsp;<code>anti_join()</code>&nbsp;knows to look for the column named&nbsp;<code>word</code>&nbsp;in each dataset.</p>
</section>
</section>
<section id="analysis-counting-words" class="level2">
<h2 class="anchored" data-anchor-id="analysis-counting-words">Analysis: Counting Words<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#analysis-counting-words" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h2>
<p>Now it’s time to start exploring our newly cleaned dataset of tweets. Computing the frequency of each word and seeing which words showed up the most often is a good start. We can pipe&nbsp;<code>tokens</code>&nbsp;to the&nbsp;<code>count</code>function to do this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="http://localhost:3849/#cb16-1" aria-hidden="true" tabindex="-1"></a>tokens <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="http://localhost:3849/#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(word, <span class="at">sort =</span> <span class="cn">TRUE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15,334 × 2
   word            n
   &lt;chr&gt;       &lt;int&gt;
 1 t.co         5432
 2 https        5406
 3 tidytuesday  4316
 4 rstats       1748
 5 data         1105
 6 code          988
 7 week          868
 8 r4ds          675
 9 dataviz       607
10 time          494
# ℹ 15,324 more rows</code></pre>
</div>
</div>
<p>We pass&nbsp;<code>count()</code>&nbsp;the argument&nbsp;<code>sort = TRUE</code>&nbsp;to sort the&nbsp;<code>n</code>&nbsp;variable from the highest value to the lowest value. This makes it easy to see the most frequently occurring words at the top. Not surprisingly, “tidytuesday” was the third most frequent word in this dataset.</p>
<p>We may want to explore further by showing the frequency of words as a percent of the whole dataset. Calculating percentages like this is useful in a lot of education scenarios because it helps us make comparisons across different sized groups. For example, you may want to calculate what percentage of students in each classroom receive special education services.</p>
<p>In our tweets dataset, we’ll be calculating the count of words as a percentage of all tweets. We can do that by using&nbsp;<code>mutate()</code>&nbsp;to add a column called&nbsp;<code>percent</code>.&nbsp;<code>percent</code>&nbsp;will divide&nbsp;<code>n</code>&nbsp;by&nbsp;<code>sum(n)</code>, which is the total number of words. Finally, will multiply the result by 100.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="http://localhost:3849/#cb18-1" aria-hidden="true" tabindex="-1"></a>tokens <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="http://localhost:3849/#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(word, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="http://localhost:3849/#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># n as a percent of total words</span></span>
<span id="cb18-4"><a href="http://localhost:3849/#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15,334 × 3
   word            n percent
   &lt;chr&gt;       &lt;int&gt;   &lt;dbl&gt;
 1 t.co         5432   7.39 
 2 https        5406   7.36 
 3 tidytuesday  4316   5.87 
 4 rstats       1748   2.38 
 5 data         1105   1.50 
 6 code          988   1.34 
 7 week          868   1.18 
 8 r4ds          675   0.919
 9 dataviz       607   0.826
10 time          494   0.672
# ℹ 15,324 more rows</code></pre>
</div>
</div>
<section id="your-turn-3" class="level3">
<h3 class="anchored" data-anchor-id="your-turn-3">Your Turn:<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#your-turn-3" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p><strong>What did you in the percentage -word table? Did you recognize anything interesting?</strong></p>
<ul>
<li><strong>A large number of tweets contained links to websites via “https”</strong></li>
</ul>
</section>
</section>
<section id="analysis-sentiment-analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis-sentiment-analysis">Analysis: Sentiment Analysis<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#analysis-sentiment-analysis" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h2>
<p>Now that we have a sense of the most frequently appearing words, it’s time to explore some questions in our tweets dataset. Let’s imagine that we’re education consultants trying to learn about the community surrounding the TidyTuesday data visualization ritual. We know from the first part of our analysis that the token “dataviz” (a short name for data visualization) appeared frequently relative to other words, so maybe we can explore that further. A good start would be to see how the appearance of that token in a tweet is associated with other positive words.</p>
<p>We’ll need to use a technique called sentiment analysis to get at the “positivity” of words in these tweets. Sentiment analysis tries to evaluate words for their emotional association. If we analyze words by the emotions they convey, we can start to explore patterns in large text datasets like our&nbsp;<code>tokens</code>&nbsp;data.</p>
<p>Earlier we used&nbsp;<code>anti_join()</code>&nbsp;to remove stop words in our dataset. We’re going to do something similar here to reduce our&nbsp;<code>tokens</code>&nbsp;dataset to only words that have a positive association. We’ll use a dataset called the <strong>NRC Word-Emotion Association Lexicon to help us identify words with a positive association</strong>. This dataset was published in a work called Crowdsourcing a Word-Emotion Association Lexicon&nbsp;(<a href="https://datascienceineducation.com/references#ref-mohammad2013">Mohammad &amp; Turney, 2013</a>)</p>
<p>We need to install a package called {textdata} to make sure we have the NRC Word-Emotion Association Lexicon dataset available to us. Note that you only need to have this package installed. You do not need to load it with the&nbsp;<code>library(textdata)</code>&nbsp;command.</p>
<p>If you don’t already have it, let’s install {textdata}:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="http://localhost:3849/#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"textdata"</span>)</span>
<span id="cb20-2"><a href="http://localhost:3849/#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(textdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To explore this dataset more, we’ll use a {tidytext} function called&nbsp;<code>get_sentiments()</code>&nbsp;to view some words and their associated sentiment. If this is your first time using the NRC Word-Emotion Association Lexicon, you’ll be prompted to download the NRC lexicon. Respond “yes” to the prompt and the NRC lexicon will download. Note that you’ll only have to do this the first time you use the NRC lexicon.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="http://localhost:3849/#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_sentiments</span>(<span class="st">"nrc"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13,872 × 2
   word        sentiment
   &lt;chr&gt;       &lt;chr&gt;    
 1 abacus      trust    
 2 abandon     fear     
 3 abandon     negative 
 4 abandon     sadness  
 5 abandoned   anger    
 6 abandoned   fear     
 7 abandoned   negative 
 8 abandoned   sadness  
 9 abandonment anger    
10 abandonment fear     
# ℹ 13,862 more rows</code></pre>
</div>
</div>
<p>This returns a dataset with two columns. The first is&nbsp;<code>word</code>&nbsp;and contains a list of words. The second is the&nbsp;<code>sentiment</code>&nbsp;column, which contains an emotion associated with each word. This dataset is similar to the&nbsp;<code>stop_words</code>&nbsp;dataset. Note that this dataset also uses the column name&nbsp;<code>word</code>, which will again make it easy for us to match this dataset to our&nbsp;<code>tokens</code>&nbsp;dataset.</p>
<section id="count-positive-words" class="level3">
<h3 class="anchored" data-anchor-id="count-positive-words">Count Positive Words<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#count-positive-words" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p>Let’s begin working on reducing our&nbsp;<code>tokens</code>&nbsp;dataset down to only words that the NRC dataset associates with positivity. We’ll start by creating a new dataset,&nbsp;<code>nrc_pos</code>, which contains the NRC words that have the positive sentiment. Then we’ll match that new dataset to&nbsp;<code>tokens</code>&nbsp;using the&nbsp;<code>word</code>&nbsp;column that is common to both datasets. Finally, we’ll use&nbsp;<code>count()</code>&nbsp;to total up the appearances of each positive word.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="http://localhost:3849/#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Only positive in the NRC dataset</span></span>
<span id="cb23-2"><a href="http://localhost:3849/#cb23-2" aria-hidden="true" tabindex="-1"></a>nrc_pos <span class="ot">&lt;-</span></span>
<span id="cb23-3"><a href="http://localhost:3849/#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_sentiments</span>(<span class="st">"nrc"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb23-4"><a href="http://localhost:3849/#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sentiment <span class="sc">==</span> <span class="st">"positive"</span>)</span>
<span id="cb23-5"><a href="http://localhost:3849/#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="http://localhost:3849/#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Match to tokens</span></span>
<span id="cb23-7"><a href="http://localhost:3849/#cb23-7" aria-hidden="true" tabindex="-1"></a>pos_tokens_count <span class="ot">&lt;-</span></span>
<span id="cb23-8"><a href="http://localhost:3849/#cb23-8" aria-hidden="true" tabindex="-1"></a>  tokens <span class="sc">%&gt;%</span></span>
<span id="cb23-9"><a href="http://localhost:3849/#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(nrc_pos, <span class="at">by =</span> <span class="st">"word"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb23-10"><a href="http://localhost:3849/#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Total appearance of positive words</span></span>
<span id="cb23-11"><a href="http://localhost:3849/#cb23-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(word, <span class="at">sort =</span> <span class="cn">TRUE</span>) </span>
<span id="cb23-12"><a href="http://localhost:3849/#cb23-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-13"><a href="http://localhost:3849/#cb23-13" aria-hidden="true" tabindex="-1"></a>pos_tokens_count</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 642 × 2
   word          n
   &lt;chr&gt;     &lt;int&gt;
 1 fun         173
 2 top         162
 3 learn       131
 4 found       128
 5 love        113
 6 community   110
 7 learning     97
 8 happy        95
 9 share        90
10 inspired     85
# ℹ 632 more rows</code></pre>
</div>
</div>
</section>
<section id="your-turn-4" class="level3">
<h3 class="anchored" data-anchor-id="your-turn-4">Your Turn:<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#your-turn-4" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p><strong>After you run the previous code chuck and observed the “pos_tokens_count”, what did this output tell you?</strong></p>
<ul>
<li><strong>Interestingly, the word “job” is considered as having positive sentiment.</strong></li>
<li>Participation as part of the “community” was a major factor for these individuals.</li>
</ul>
<p>We can visualize these words nicely by using {ggplot2} to show the positive words in a bar chart. There are 644 words total, which is hard to convey in a compact chart. We’ll solve that problem by filtering our dataset to only words that appear 75 times or more.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="http://localhost:3849/#cb25-1" aria-hidden="true" tabindex="-1"></a>pos_tokens_count <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="http://localhost:3849/#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># only words that appear 75 times or more</span></span>
<span id="cb25-3"><a href="http://localhost:3849/#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&gt;=</span> <span class="dv">75</span>) <span class="sc">|&gt;</span></span>
<span id="cb25-4"><a href="http://localhost:3849/#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(word, <span class="sc">-</span>n), <span class="at">y =</span> n)) <span class="sc">+</span></span>
<span id="cb25-5"><a href="http://localhost:3849/#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb25-6"><a href="http://localhost:3849/#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb25-7"><a href="http://localhost:3849/#cb25-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Count of Words Associated with Positivity"</span>,</span>
<span id="cb25-8"><a href="http://localhost:3849/#cb25-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Tweets with the hashtag #tidytuesday"</span>,</span>
<span id="cb25-9"><a href="http://localhost:3849/#cb25-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Data: Twitter and NRC"</span>,</span>
<span id="cb25-10"><a href="http://localhost:3849/#cb25-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb25-11"><a href="http://localhost:3849/#cb25-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span></span>
<span id="cb25-12"><a href="http://localhost:3849/#cb25-12" aria-hidden="true" tabindex="-1"></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="./Unit4_RTutorial Week_files/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="dataviz-and-other-positive-words" class="level3">
<h3 class="anchored" data-anchor-id="dataviz-and-other-positive-words">“Dataviz” and Other Positive Words<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#dataviz-and-other-positive-words" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p>Earlier in the analysis we learned that “dataviz” was among the most frequently occurring words in this dataset. We can continue our exploration of TidyTuesday tweets by seeing how many tweets with “dataviz” also had at least one positive word from the NRC dataset. Looking at this might give us some clues about how people in the TidyTuesday learning community view dataviz as a tool.</p>
<p>There are a few steps to this part of the analysis, so let’s review our strategy. We’ll need to use the&nbsp;<code>status_id</code>&nbsp;field in the&nbsp;<code>tweets</code>&nbsp;dataset to filter the tweets that have the word&nbsp;<code>dataviz</code>&nbsp;in them. Then we need to use the&nbsp;<code>status_id</code>&nbsp;field in this new bunch of&nbsp;<code>dataviz</code>&nbsp;tweets to identify the tweets that include at least one positive word.</p>
<p>How do we know which&nbsp;<code>status_id</code>&nbsp;values contain the word “dataviz” and which ones contain a positive word? Recall that our&nbsp;<code>tokens</code>&nbsp;dataset only has one word per row, which makes it easy to use functions like&nbsp;<code>filter()</code>&nbsp;and&nbsp;<code>inner_join()</code>&nbsp;to make two new datasets: one of&nbsp;<code>status_id</code>&nbsp;values that have “dataviz” in the&nbsp;<code>word</code>&nbsp;column and one of&nbsp;<code>status_id</code>&nbsp;values that have a positive word in the&nbsp;<code>word</code>&nbsp;column.</p>
<p>We’ll explore the combinations of “dataviz” and any positive words in our&nbsp;<code>tweets</code>&nbsp;dataset using these three ingredients: our&nbsp;<code>tweets</code>&nbsp;dataset, a vector of&nbsp;<code>status_id</code>s for tweets that have “dataviz” in them, and a vector of&nbsp;<code>status_id</code>s for tweets that have positive words in them. Now that we have our strategy, let’s write some code and see how it works.</p>
<p>First, we’ll make a vector of&nbsp;<code>status_id</code>s for tweets that have “dataviz” in them. This will be used later to identify tweets that contain “dataviz” in the text. We’ll use&nbsp;<code>filter()</code>&nbsp;on our&nbsp;<code>tokens</code>&nbsp;dataset to keep only the rows that have “dataviz” in the&nbsp;<code>word</code>&nbsp;column. Let’s name that new dataset&nbsp;<code>dv_tokens</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="http://localhost:3849/#cb26-1" aria-hidden="true" tabindex="-1"></a>dv_tokens <span class="ot">&lt;-</span></span>
<span id="cb26-2"><a href="http://localhost:3849/#cb26-2" aria-hidden="true" tabindex="-1"></a>  tokens <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="http://localhost:3849/#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(word <span class="sc">==</span> <span class="st">"dataviz"</span>)</span>
<span id="cb26-4"><a href="http://localhost:3849/#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="http://localhost:3849/#cb26-5" aria-hidden="true" tabindex="-1"></a>dv_tokens</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 607 × 2
   status_id           word   
   &lt;chr&gt;               &lt;chr&gt;  
 1 1116518351147360257 dataviz
 2 1098025772554612738 dataviz
 3 1161454327296339968 dataviz
 4 1110711892086001665 dataviz
 5 1151926405162291200 dataviz
 6 1095854400004853765 dataviz
 7 1157111441419395074 dataviz
 8 1154958378764046336 dataviz
 9 1105642831413239808 dataviz
10 1108196618464047105 dataviz
# ℹ 597 more rows</code></pre>
</div>
</div>
<p>The result is a dataset that has status_ids in one column and the word “dataviz” in the other column. We can use&nbsp;<code>$</code>&nbsp;to extract a vector of status_ids for tweets that have “dataviz” in the text. This vector has hundreds of values, so we’ll use&nbsp;<code>head</code>&nbsp;to view just the first six.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="http://localhost:3849/#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract status_id</span></span>
<span id="cb28-2"><a href="http://localhost:3849/#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dv_tokens<span class="sc">$</span>status_id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "1116518351147360257" "1098025772554612738" "1161454327296339968"
[4] "1110711892086001665" "1151926405162291200" "1095854400004853765"</code></pre>
</div>
</div>
<p>Now let’s do this again, but this time we’ll we’ll make a vector of&nbsp;<code>status_id</code>s for tweets that have positive words in them. This will be used later to identify tweets that contain a positive word in the text. We’ll use&nbsp;<code>filter()</code>&nbsp;on our&nbsp;<code>tokens</code>&nbsp;dataset to keep only the rows that have any of the positive words in the in the&nbsp;<code>word</code>&nbsp;column. If you’ve been running all the code up to this point in the walkthrough, you’ll notice that you already have a dataset of positive words called&nbsp;<code>nrc_pos</code>, which can be turned into a vector of positive words by typing&nbsp;<code>nrc_pos$word</code>. We can use the&nbsp;<code>%in%</code>&nbsp;operator in our call to&nbsp;<code>filter()</code>&nbsp;to find only words that are in this vector of positive words. Let’s name this new dataset&nbsp;<code>pos_tokens</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="http://localhost:3849/#cb30-1" aria-hidden="true" tabindex="-1"></a>pos_tokens <span class="ot">&lt;-</span> </span>
<span id="cb30-2"><a href="http://localhost:3849/#cb30-2" aria-hidden="true" tabindex="-1"></a>  tokens <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="http://localhost:3849/#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(word <span class="sc">%in%</span> nrc_pos<span class="sc">$</span>word)</span>
<span id="cb30-4"><a href="http://localhost:3849/#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="http://localhost:3849/#cb30-5" aria-hidden="true" tabindex="-1"></a>pos_tokens</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,885 × 2
   status_id           word      
   &lt;chr&gt;               &lt;chr&gt;     
 1 1163154266065735680 throne    
 2 1001412196247666688 honey     
 3 1001412196247666688 production
 4 1001412196247666688 increase  
 5 1001412196247666688 production
 6 1161638973808287746 found     
 7 991073965899644928  community 
 8 991073965899644928  community 
 9 991073965899644928  trend     
10 991073965899644928  population
# ℹ 4,875 more rows</code></pre>
</div>
</div>
<p>The result is a dataset that has status_ids in one column and a positive word from&nbsp;<code>tokens</code>&nbsp;in the other column. We’ll again use&nbsp;<code>$</code>&nbsp;to extract a vector of status_ids for these tweets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="http://localhost:3849/#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract status_id</span></span>
<span id="cb32-2"><a href="http://localhost:3849/#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pos_tokens<span class="sc">$</span>status_id) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "1163154266065735680" "1001412196247666688" "1001412196247666688"
[4] "1001412196247666688" "1001412196247666688" "1161638973808287746"</code></pre>
</div>
</div>
<p>That’s a lot of&nbsp;<code>status_id</code>s, many of which are duplicates. Let’s try and make the vector of&nbsp;<code>status_id</code>s a little shorter. We can use&nbsp;<code>distinct()</code>&nbsp;to get a data frame of&nbsp;<code>status_id</code>s, where each&nbsp;<code>status_id</code>&nbsp;only appears once:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="http://localhost:3849/#cb34-1" aria-hidden="true" tabindex="-1"></a>pos_tokens <span class="ot">&lt;-</span></span>
<span id="cb34-2"><a href="http://localhost:3849/#cb34-2" aria-hidden="true" tabindex="-1"></a>  pos_tokens <span class="sc">%&gt;%</span> </span>
<span id="cb34-3"><a href="http://localhost:3849/#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(status_id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that&nbsp;<code>distinct()</code>&nbsp;drops all variables except for&nbsp;<code>status_id</code>. For good measure, let’s use&nbsp;<code>distinct()</code>&nbsp;on our&nbsp;<code>dv_tokens</code>&nbsp;data frame too:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="http://localhost:3849/#cb35-1" aria-hidden="true" tabindex="-1"></a>dv_tokens <span class="ot">&lt;-</span></span>
<span id="cb35-2"><a href="http://localhost:3849/#cb35-2" aria-hidden="true" tabindex="-1"></a>  dv_tokens <span class="sc">%&gt;%</span> </span>
<span id="cb35-3"><a href="http://localhost:3849/#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(status_id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we have a data frame of&nbsp;<code>status_id</code>&nbsp;for tweets containing “dataviz” and another for tweets containing a positive word. Let’s use these to transform our&nbsp;<code>tweets</code>&nbsp;dataset. First we’ll filter&nbsp;<code>tweets</code>&nbsp;for rows that have the “dataviz”&nbsp;<code>status_id</code>. Then we’ll create a new column called&nbsp;<code>positive</code>&nbsp;that will tell us if the&nbsp;<code>status_id</code>&nbsp;is from our vector of positive word&nbsp;<code>status_id</code>s. We’ll name this filtered dataset&nbsp;<code>dv_pos</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="http://localhost:3849/#cb36-1" aria-hidden="true" tabindex="-1"></a>dv_pos <span class="ot">&lt;-</span></span>
<span id="cb36-2"><a href="http://localhost:3849/#cb36-2" aria-hidden="true" tabindex="-1"></a>  tweets <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="http://localhost:3849/#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Only tweets that have the dataviz status_id</span></span>
<span id="cb36-4"><a href="http://localhost:3849/#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(status_id <span class="sc">%in%</span> dv_tokens<span class="sc">$</span>status_id) <span class="sc">%&gt;%</span></span>
<span id="cb36-5"><a href="http://localhost:3849/#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Is the status_id from our vector of positive word?</span></span>
<span id="cb36-6"><a href="http://localhost:3849/#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">positive =</span> <span class="fu">if_else</span>(status_id <span class="sc">%in%</span> pos_tokens<span class="sc">$</span>status_id, <span class="dv">1</span>, <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s take a moment to dissect how we use&nbsp;<code>if_else()</code>&nbsp;to create our&nbsp;<code>positive</code>&nbsp;column. We gave&nbsp;<code>if_else()</code>&nbsp;three arguments:</p>
<ul>
<li><p><code>status_id %in% pos_tokens$status_id</code>: a logical statement</p></li>
<li><p><code>1</code>: the value of&nbsp;<code>positive</code>&nbsp;if the logical statement is true</p></li>
<li><p><code>0</code>: the value of&nbsp;<code>positive</code>&nbsp;if the logical statement is false</p></li>
</ul>
<p>So our new&nbsp;<code>positive</code>&nbsp;column will take the value 1 if the&nbsp;<code>status_id</code>&nbsp;was in our&nbsp;<code>pos_tokens</code>&nbsp;dataset and the value 0 if the&nbsp;<code>status_id</code>&nbsp;was not in our&nbsp;<code>pos_tokens</code>&nbsp;dataset. Practically speaking,&nbsp;<code>positive</code>&nbsp;is 1 if the tweet has a positive word and 0 if it does not have a positive word.</p>
<p>And finally, let’s see what percent of tweets that had “dataviz” in them also had at least one positive word:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="http://localhost:3849/#cb37-1" aria-hidden="true" tabindex="-1"></a>dv_pos <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="http://localhost:3849/#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(positive) <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="http://localhost:3849/#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">perc =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  positive     n  perc
     &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt;
1        0   272 0.450
2        1   333 0.550</code></pre>
</div>
</div>
</section>
<section id="your-turn-5" class="level3">
<h3 class="anchored" data-anchor-id="your-turn-5">Your Turn:<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#your-turn-5" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p><strong>The table above represents the percent of tweets that had “dataviz”, can you please interpret the result of the table and tell what did you discover at the end of this analysis?</strong></p>
<p><strong>Your Response Here:</strong></p>
<p>It seems as though a majority of users use the term “dataviz” are potentially positive. This is not very reliable because sentiment can be more complicated than the presence of a word in a statement. What can be confirmed is that overall the opinion is mixed.</p>
<p>Since the point of exploratory data analysis is to explore and develop questions, let’s continue to do that. In this last section we’ll review a random selection of tweets for context.</p>
</section>
<section id="taking-a-close-read-of-randomly-selected-tweets" class="level3">
<h3 class="anchored" data-anchor-id="taking-a-close-read-of-randomly-selected-tweets">Taking A Close Read of Randomly Selected Tweets<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#taking-a-close-read-of-randomly-selected-tweets" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p>Let’s review where we are so far as we work to learn more about the TidyTuesday learning community through tweets. So far we’ve counted frequently used words and estimated the number of tweets with positive associations. This dataset is large, so we need to zoom out and find ways to summarize the data. But it’s also useful to explore by zooming in and reading some of the tweets. Reading tweets helps us to build intuition and context about how users talk about TidyTuesday in general. Even though this doesn’t lead to quantitative findings, it helps us to learn more about the content we’re studying and analyzing. Instead of reading all 4418 tweets, let’s write some code to randomly select tweets to review.</p>
<p>First, let’s make a dataset of tweets that had positive words from the NRC dataset. Remember earlier when we made a dataset of tweets that had “dataviz” and a column that had a value of 1 for containing positive words and 0 for not containing positive words? Let’s reuse that technique, but instead of applying to a dataset of tweets containing “dataviz”, let’s use it on our dataset of all tweets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="http://localhost:3849/#cb39-1" aria-hidden="true" tabindex="-1"></a>pos_tweets <span class="ot">&lt;-</span></span>
<span id="cb39-2"><a href="http://localhost:3849/#cb39-2" aria-hidden="true" tabindex="-1"></a>  tweets <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="http://localhost:3849/#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">positive =</span> <span class="fu">if_else</span>(status_id <span class="sc">%in%</span> pos_tokens<span class="sc">$</span>status_id, <span class="dv">1</span>, <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="http://localhost:3849/#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(positive <span class="sc">==</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Again, we’re using&nbsp;<code>if_else</code>&nbsp;to make a new column called&nbsp;<code>positive</code>&nbsp;that takes its value based on whether&nbsp;<code>status_id %in% pos_tokens$status_id</code>&nbsp;is true or not.</p>
<p>We can use&nbsp;<code>slice()</code>&nbsp;to help us pick the rows. When we pass&nbsp;<code>slice()</code>&nbsp;a row number, it returns that row from the dataset. For example, we can select the 1st and 3rd row of our tweets dataset this way:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="http://localhost:3849/#cb40-1" aria-hidden="true" tabindex="-1"></a>tweets <span class="sc">%&gt;%</span> </span>
<span id="cb40-2"><a href="http://localhost:3849/#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span>, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  status_id           text                                                      
  &lt;chr&gt;               &lt;chr&gt;                                                     
1 1163154266065735680 "First #TidyTuesday submission! Roman emperors and their …
2 1001412196247666688 "My #tidytuesday submission for week 8. Honey production …</code></pre>
</div>
</div>
<p>Randomly selecting rows from a dataset is great technique to have in your toolkit. Random selection helps us avoid some of the biases we all have when we pick rows to review ourselves.</p>
<p>Here’s one way to do that using base R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="http://localhost:3849/#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">size =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  3  9  5 10  7</code></pre>
</div>
</div>
<p>Passing&nbsp;<code>sample()</code>&nbsp;a vector of numbers and the size of the sample you want returns a random selection from the vector. Try changing the value of&nbsp;<code>x</code>&nbsp;and&nbsp;<code>size</code>&nbsp;to see how this works.</p>
<p>{dplyr} has a version of this called&nbsp;<code>sample_n()</code>&nbsp;that we can use to randomly select rows in our tweets dataset. Using&nbsp;<code>sample_n()</code>&nbsp;looks like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="http://localhost:3849/#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2020</span>)</span>
<span id="cb44-2"><a href="http://localhost:3849/#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="http://localhost:3849/#cb44-3" aria-hidden="true" tabindex="-1"></a>pos_tweets <span class="sc">%&gt;%</span> </span>
<span id="cb44-4"><a href="http://localhost:3849/#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(., <span class="at">size =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   status_id           text                                             positive
   &lt;chr&gt;               &lt;chr&gt;                                               &lt;dbl&gt;
 1 1133817727615930369 "@allison_horst @thomas_mock I wonder if there …        1
 2 1146039959725518848 "⁣⁣⁣⁣⁣⁣Follow @House_of_Honda⁣⁣⁣⁣\n⁣⁣⁣\n⁣⁣⁣⁣\n\U0001f530 This FB…        1
 3 988608513663528960  "#TidyTuesday\nI know there must be far easier …        1
 4 1117623421012205568 "#TidyTuesday #rstats Week 2019-04-09: 50 years…        1
 5 1029834250063945728 "Following my previous tweet, I took a deep div…        1
 6 1141050762337882112 "1960: the year owls with extreme-length ears r…        1
 7 1118668150780907520 "A simple #TidyTuesday submission this week. A …        1
 8 993149495193100288  "@TheresaWege Great visualization Theresa! Than…        1
 9 1117692475135520768 "#TidyTuesday inspired by @sil_aarts https://t.…        1
10 1143570115864211456 "Had another go at the #tidytuesday bird count …        1</code></pre>
</div>
</div>
<p>That returned ten randomly selected tweets that we can now read through and discuss. Let’s look a little closer at how we did that. We used&nbsp;<code>sample_n()</code>, which returns randomly selected rows from our tweets dataset. We also specified that&nbsp;<code>size = 10</code>, which means we want&nbsp;<code>sample_n()</code>&nbsp;to give us 10 randomly selected rows. A few lines before that, we used&nbsp;<code>set.seed(2020)</code>. This helps us ensure that, while&nbsp;<code>sample_n()</code>theoretically plucks 10 random numbers, our readers can run this code and get the same result we did. Using&nbsp;<code>set.seed(2020)</code>&nbsp;at the top of your code makes&nbsp;<code>sample_n()</code>&nbsp;pick the same ten rows every time. Try changing&nbsp;<code>2020</code>&nbsp;to another number and notice how&nbsp;<code>sample_n()</code>&nbsp;picks a different set of ten numbers, but repeatedly picks those numbers until you change the argument in&nbsp;<code>set.seed()</code>.</p>
</section>
</section>
<section id="summary-of-walkthrough-5" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-walkthrough-5">Summary of Walkthrough 5<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#summary-of-walkthrough-5" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h2>
<p>The purpose of this walkthrough is to share code with you so you can practice some basic text analysis techniques. Now it’s time to make your learning more meaningful by adapting this code to text-based files you regularly see at work. Trying reading in some of these and doing a similar analysis:</p>
<ul>
<li><p>News articles</p></li>
<li><p>Procedure manuals</p></li>
<li><p>Open ended responses in surveys</p></li>
</ul>
<p>There are also advanced text analysis techniques to explore. Consider trying topic modeling (<a href="https://www.tidytextmining.com/topicmodeling.html" class="uri">https://www.tidytextmining.com/topicmodeling.html</a>) or finding correlations between terms (<a href="https://www.tidytextmining.com/ngrams.html" class="uri">https://www.tidytextmining.com/ngrams.html</a>), both described in&nbsp;(<a href="https://datascienceineducation.com/references#ref-silge2017text">Silge &amp; Robinson, 2017</a>).</p>
<p>Finally, if you feel like there is more to analyze where it comes to this particular hashtag, we agree! We use this data set further in the next chapter&nbsp;<a href="https://datascienceineducation.com/c12#c12">on social network analysis</a>. Moreover, if you want to collect our own Twitter data, head to&nbsp;<a href="https://datascienceineducation.com/c11#c20b">Appendix B</a>&nbsp;to read about and consider some potential strategies.</p>
</section>
</section>
<section id="walkthrough-6-exploring-relationships-using-social-network-analysis-with-social-media-data" class="level1">
<h1>Walkthrough 6: Exploring Relationships Using Social Network Analysis With Social Media Data</h1>
<section id="topics-emphasized-1" class="level3">
<h3 class="anchored" data-anchor-id="topics-emphasized-1">Topics Emphasized<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#topics-emphasized-1" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<ul>
<li><p>Transforming data</p></li>
<li><p>Visualizing data</p></li>
</ul>
</section>
<section id="functions-introduced-1" class="level3">
<h3 class="anchored" data-anchor-id="functions-introduced-1">Functions Introduced<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#functions-introduced-1" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<ul>
<li><p><code>rtweet::search_tweets()</code></p></li>
<li><p><code>randomNames::randomNames()</code></p></li>
<li><p><code>tidyr::unnest()</code></p></li>
<li><p><code>tidygraph::as_tbl_graph()</code></p></li>
<li><p><code>ggraph::ggraph()</code></p></li>
</ul>
</section>
<section id="vocabulary-1" class="level3">
<h3 class="anchored" data-anchor-id="vocabulary-1">Vocabulary<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#vocabulary-1" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<ul>
<li><p>Application Programming Interface (API)</p></li>
<li><p>edgelist</p></li>
<li><p>edge</p></li>
<li><p>influence model</p></li>
<li><p>regex</p></li>
<li><p>selection model</p></li>
<li><p>social network analysis</p></li>
<li><p>sociogram</p></li>
<li><p>vertex</p></li>
</ul>
</section>
<section id="chapter-overview-1" class="level2">
<h2 class="anchored" data-anchor-id="chapter-overview-1">Chapter Overview<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#chapter-overview-1" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h2>
<p>In the previous walkthrough, we focused on using text analysis to understand the&nbsp;<em>content</em>&nbsp;of tweets. In this, we focus on the&nbsp;<em>interactions</em>&nbsp;between #tidytuesday participants using social network analysis techniques.</p>
<p>While social network analysis is increasingly common, it remains challenging to carry out. For one, cleaning and tidying the data can be even more challenging than for most other data sources, as net data for social network analysis (or network data) often includes variables about both individuals (such as information students or teachers) and their relationships (whether they have a relationship at all, for example, or how strong or of what type their relationship is). This chapter is designed to take you from not having carried out social network analysis through visualizing network data.</p>
<section id="background-1" class="level3">
<h3 class="anchored" data-anchor-id="background-1">Background<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#background-1" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p>There are a few reasons to be interested in social media. For example, if you work in a school district, you may want to know who is interacting with the content you share. If you are a researcher, you may want to investigate what teachers, administrators, and others do through state-based hashtags (e.g.,&nbsp;Joshua M. Rosenberg et al.&nbsp;(<a href="https://datascienceineducation.com/references#ref-rosenberg2016">2016</a>)). Social media-based data also provides new contexts for learning to take place, like in professional learning networks&nbsp;(<a href="https://datascienceineducation.com/references#ref-trust2016">Trust et al., 2016</a>).</p>
<p>In the past, if a teacher wanted advice about how to plan a unit or to design a lesson, they would turn to a trusted peer in their building or district&nbsp;(<a href="https://datascienceineducation.com/references#ref-spillane2012">Spillane et al., 2012</a>). Today they are as likely to turn to someone in a social media network. Social media interactions like the ones tagged with the #tidytuesday hashtag are increasingly common in education. Using data science tools to learn from these interactions is valuable for improving the student experience.</p>
</section>
<section id="packages" class="level3">
<h3 class="anchored" data-anchor-id="packages">Packages<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#packages" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p>In this chapter, we access data using the {rtweet} package&nbsp;(<a href="https://datascienceineducation.com/references#ref-kearney2016">Michael W. Kearney, 2016</a>). Through {rtweet} and a Twitter account, it is easy to access data from Twitter. We will load the {tidyverse} and {rtweet} packages to get started.</p>
<p>We will also load other packages that we will be using in this analysis, including two packages related to social network analysis&nbsp;(<a href="https://datascienceineducation.com/references#ref-R-tidygraph">Pedersen, 2022b</a>,&nbsp;<a href="https://datascienceineducation.com/references#ref-R-ggraph">2022a</a>)&nbsp;as well as one that will help us to use not-anonymized names in a savvy way&nbsp;(<a href="https://datascienceineducation.com/references#ref-R-randomNames">Betebenner, 2021</a>). As always, if you have not installed any of these packages before (which may particularly be the case for the {rtweet}, {randomNames}, {tidygraph}, and {ggraph} packages, which we have not yet used int he book), do so using the&nbsp;<code>install.packages()</code>&nbsp;function. More on installing packages is included in the&nbsp;<a href="https://datascienceineducation.com/c06#c06p">Packages</a>&nbsp;section of the&nbsp;<a href="https://datascienceineducation.com/c06#c06">Foundational Skills</a>&nbsp;chapter.</p>
<p>Let’s load the packages with the following calls to the&nbsp;<code>library()</code>&nbsp;function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="http://localhost:3849/#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rtweet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'rtweet'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    flatten</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="http://localhost:3849/#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dataedu)</span>
<span id="cb49-2"><a href="http://localhost:3849/#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomNames)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'randomNames' was built under R version 4.3.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="http://localhost:3849/#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidygraph)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidygraph' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'tidygraph'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:stats':

    filter</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="http://localhost:3849/#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggraph)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggraph' was built under R version 4.3.2</code></pre>
</div>
</div>
</section>
<section id="data-sources-and-import" class="level3">
<h3 class="anchored" data-anchor-id="data-sources-and-import">Data Sources and Import<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#data-sources-and-import" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p>Here is an example of searching the most recent 1,000 tweets which include the hashtag #rstats. When you run this code, you will be prompted to authenticate your access via Twitter.</p>
<p>You can find a greater number of tweets by adding a greater value to the&nbsp;<code>n</code>&nbsp;argument of the&nbsp;<code>search_tweets()</code>&nbsp;function, as follows, to collect the most recent 500 tweets:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="http://localhost:3849/#cb57-1" aria-hidden="true" tabindex="-1"></a>tt_tweets <span class="ot">&lt;-</span> dataedu<span class="sc">::</span>tt_tweets</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="view-data" class="level3">
<h3 class="anchored" data-anchor-id="view-data">View Data<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#view-data" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
</section>
<section id="your-turn-6" class="level3">
<h3 class="anchored" data-anchor-id="your-turn-6">Your Turn<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#your-turn-6" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p>View the tt_tweets data with nrow() or glimpse() functions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="http://localhost:3849/#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(tt_tweets)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4418</code></pre>
</div>
</div>
</section>
</section>
<section id="methods-process-data" class="level2">
<h2 class="anchored" data-anchor-id="methods-process-data">Methods: Process Data<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#methods-process-data" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h2>
<p>Network data requires some processing before it can be used in subsequent analyses. The network dataset needs a way to identify each participant’s role in the interaction. We need to answer questions like:</p>
<ul>
<li><p>Did someone reach out to another for help?</p></li>
<li><p>Was someone contacted by another for help?</p></li>
</ul>
<p>We can process the data by creating an&nbsp;<em>edgelist</em>. An edgelist is a dataset where each row is a unique interaction between two parties. Each row (which represents a single relationship) in the edgelist is referred to as an&nbsp;<em>edge</em>. We note that one challenge facing data scientists beginning to use network analysis is the different terms that are used for similar (or the same!) aspects of analyses: Edges are sometimes referred to as&nbsp;<em>ties</em>&nbsp;or&nbsp;<em>relations</em>, but these generally refer to the same thing, though they may be used in different contexts.</p>
<p>An edgelist looks like the following, where the&nbsp;<code>sender</code>&nbsp;(sometimes called the “nominator”) column identifies who is initiating the interaction and the&nbsp;<code>receiver</code>&nbsp;(sometimes called the “nominee”) column identifies who is receiving the interaction:</p>
<p><img src="./Unit4_RTutorial Week_files/Edgelist_img.png" class="img-fluid" width="522"></p>
<p>In this edgelist, the&nbsp;<code>sender</code>&nbsp;column might identify someone who nominates another (the receiver) as someone they go to for help. The sender might also identify someone who interacts with the receiver in other ways, like “liking” or “mentioning” their tweets. In the following steps, we will work to create an edgelist from the data from #tidytuesday on Twitter.</p>
<section id="extracting-mentions" class="level3">
<h3 class="anchored" data-anchor-id="extracting-mentions">Extracting Mentions<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#extracting-mentions" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p>Let’s extract the mentions. There is a lot going on in the code below; let’s break it down line-by-line, starting with&nbsp;<code>mutate()</code>:</p>
<ul>
<li><p><code>mutate(all_mentions = str_extract_all(text, regex))</code>: this line uses a regex, or regular expression, to identify all of the usernames in the tweet (<em>note</em>: the regex comes from from&nbsp;<a href="https://stackoverflow.com/questions/18164839/get-twitter-username-with-regex-in-r">this Stack Overflow page</a>&nbsp;(https://stackoverflow.com/questions/18164839/get-twitter-username-with-regex-in-r))</p></li>
<li><p><code>unnest(all_mentions)</code>&nbsp;this line uses a {tidyr} function,&nbsp;<code>unnest()</code>&nbsp;to move every mention to its own line, while keeping all of the other information the same (see more about&nbsp;<code>unnest()</code>&nbsp;here:&nbsp;<a href="https://tidyr.tidyverse.org/reference/unnest.html" class="uri">https://tidyr.tidyverse.org/reference/unnest.html</a>)).</p></li>
</ul>
<p>Now let’s use these functions to extract the mentions from the dataset. Here’s how all the code looks in action:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="http://localhost:3849/#cb60-1" aria-hidden="true" tabindex="-1"></a>regex <span class="ot">&lt;-</span> <span class="st">"@([A-Za-z]+[A-Za-z0-9_]+)(?![A-Za-z0-9_]*</span><span class="sc">\\</span><span class="st">.)"</span></span>
<span id="cb60-2"><a href="http://localhost:3849/#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="http://localhost:3849/#cb60-3" aria-hidden="true" tabindex="-1"></a>tt_tweets <span class="ot">&lt;-</span></span>
<span id="cb60-4"><a href="http://localhost:3849/#cb60-4" aria-hidden="true" tabindex="-1"></a>  tt_tweets <span class="sc">%&gt;%</span></span>
<span id="cb60-5"><a href="http://localhost:3849/#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Use regular expression to identify all the usernames in a tweet</span></span>
<span id="cb60-6"><a href="http://localhost:3849/#cb60-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">all_mentions =</span> <span class="fu">str_extract_all</span>(text, regex)) <span class="sc">%&gt;%</span></span>
<span id="cb60-7"><a href="http://localhost:3849/#cb60-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(all_mentions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s put these into their own data frame, called&nbsp;<code>mentions</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="http://localhost:3849/#cb61-1" aria-hidden="true" tabindex="-1"></a>mentions <span class="ot">&lt;-</span></span>
<span id="cb61-2"><a href="http://localhost:3849/#cb61-2" aria-hidden="true" tabindex="-1"></a>  tt_tweets <span class="sc">%&gt;%</span></span>
<span id="cb61-3"><a href="http://localhost:3849/#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">all_mentions =</span> <span class="fu">str_trim</span>(all_mentions)) <span class="sc">%&gt;%</span></span>
<span id="cb61-4"><a href="http://localhost:3849/#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">sender =</span> screen_name, all_mentions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="putting-the-edgelist-together" class="level3">
<h3 class="anchored" data-anchor-id="putting-the-edgelist-together">Putting the Edgelist Together<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#putting-the-edgelist-together" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p>Recall that an edgelist is a data structure that has columns for the “sender” and “receiver” of interactions. Someone “sends” the mention to someone who is mentioned, who can be considered to “receive” it. To make the edgelist, we’ll need to clean it up a little by removing the “@” symbol. Let’s look at our data as it is now.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="http://localhost:3849/#cb62-1" aria-hidden="true" tabindex="-1"></a>mentions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,447 × 2
   sender  all_mentions    
   &lt;chr&gt;   &lt;chr&gt;           
 1 cizzart @eldestapeweb   
 2 cizzart @INDECArgentina 
 3 cizzart @ENACOMArgentina
 4 cizzart @tribunalelecmns
 5 cizzart @CamaraElectoral
 6 cizzart @INDECArgentina 
 7 cizzart @tribunalelecmns
 8 cizzart @CamaraElectoral
 9 cizzart @AgroMnes       
10 cizzart @AgroindustriaAR
# ℹ 2,437 more rows</code></pre>
</div>
</div>
<p>Let’s remove that “@” symbol from the columns we created and save the results to a new tibble,&nbsp;<code>edgelist</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="http://localhost:3849/#cb64-1" aria-hidden="true" tabindex="-1"></a>edgelist <span class="ot">&lt;-</span> </span>
<span id="cb64-2"><a href="http://localhost:3849/#cb64-2" aria-hidden="true" tabindex="-1"></a>  mentions <span class="sc">%&gt;%</span> </span>
<span id="cb64-3"><a href="http://localhost:3849/#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># remove "@" from all_mentions column</span></span>
<span id="cb64-4"><a href="http://localhost:3849/#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">all_mentions =</span> <span class="fu">str_sub</span>(all_mentions, <span class="at">start =</span> <span class="dv">2</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb64-5"><a href="http://localhost:3849/#cb64-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># rename all_mentions to receiver</span></span>
<span id="cb64-6"><a href="http://localhost:3849/#cb64-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sender, <span class="at">receiver =</span> all_mentions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="analysis-and-results" class="level2">
<h2 class="anchored" data-anchor-id="analysis-and-results">Analysis and Results<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#analysis-and-results" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h2>
<p>Now that we have our edgelist, let’s plot the network. We’ll use the {tidygraph} and {ggraph} packages to visualize the data. We note that network visualizations are often referred to as&nbsp;<em>sociograms</em>, or a representation of the relationships between individuals in a network. We use this term and the term network visualization interchangeably in this chapter.</p>
<section id="plotting-the-network" class="level3">
<h3 class="anchored" data-anchor-id="plotting-the-network">Plotting the Network<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#plotting-the-network" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p>Large networks like this one can be hard to work with because of their size. We can get around that problem by only include some individuals. Let’s explore how many interactions each individual in the network sent by using&nbsp;<code>count()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="http://localhost:3849/#cb65-1" aria-hidden="true" tabindex="-1"></a>interactions_sent <span class="ot">&lt;-</span> edgelist <span class="sc">%&gt;%</span> </span>
<span id="cb65-2"><a href="http://localhost:3849/#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># this counts how many times each sender appears in the data frame, effectively counting how many interactions each individual sent </span></span>
<span id="cb65-3"><a href="http://localhost:3849/#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(sender) <span class="sc">%&gt;%</span> </span>
<span id="cb65-4"><a href="http://localhost:3849/#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># arranges the data frame in descending order of the number of interactions sent</span></span>
<span id="cb65-5"><a href="http://localhost:3849/#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span>
<span id="cb65-6"><a href="http://localhost:3849/#cb65-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-7"><a href="http://localhost:3849/#cb65-7" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(interactions_sent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="your-turn-7" class="level3">
<h3 class="anchored" data-anchor-id="your-turn-7">Your Turn:<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#your-turn-7" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p><strong>What is your first impressions related to “interactions_sent” data frame?</strong></p>
<p><strong>Your Response: thomas_mock and mjhendrickson have a lot of time on their hands. Or rather perhaps they were moderators as they have a number of interactions exceeding any other participants.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="http://localhost:3849/#cb66-1" aria-hidden="true" tabindex="-1"></a>interactions_sent <span class="ot">&lt;-</span> </span>
<span id="cb66-2"><a href="http://localhost:3849/#cb66-2" aria-hidden="true" tabindex="-1"></a>  interactions_sent <span class="sc">%&gt;%</span> </span>
<span id="cb66-3"><a href="http://localhost:3849/#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>That leaves us with only 349, which will be much easier to work with.</p>
<p>We now need to filter the edgelist to only include these 349 individuals. The following code uses the&nbsp;<code>filter()</code>&nbsp;function combined with the&nbsp;<code>%in%</code>&nbsp;operator to do this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="http://localhost:3849/#cb67-1" aria-hidden="true" tabindex="-1"></a>edgelist <span class="ot">&lt;-</span> edgelist <span class="sc">%&gt;%</span> </span>
<span id="cb67-2"><a href="http://localhost:3849/#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># the first of the two lines below filters to include only senders in the interactions_sent data frame</span></span>
<span id="cb67-3"><a href="http://localhost:3849/#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># the second line does the same, for receivers</span></span>
<span id="cb67-4"><a href="http://localhost:3849/#cb67-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sender <span class="sc">%in%</span> interactions_sent<span class="sc">$</span>sender,</span>
<span id="cb67-5"><a href="http://localhost:3849/#cb67-5" aria-hidden="true" tabindex="-1"></a>         receiver <span class="sc">%in%</span> interactions_sent<span class="sc">$</span>sender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We’ll use the&nbsp;<code>as_tbl_graph()</code>&nbsp;function, which identifies the first column as the “sender” and the second as the “receiver.” Let’s look at the object it creates:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="http://localhost:3849/#cb68-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> </span>
<span id="cb68-2"><a href="http://localhost:3849/#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tbl_graph</span>(edgelist)</span>
<span id="cb68-3"><a href="http://localhost:3849/#cb68-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-4"><a href="http://localhost:3849/#cb68-4" aria-hidden="true" tabindex="-1"></a>g</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tbl_graph: 267 nodes and 975 edges
#
# A directed multigraph with 7 components
#
# A tibble: 267 × 1
  name           
  &lt;chr&gt;          
1 dgwinfred      
2 datawookie     
3 jvaghela4      
4 FournierJohanie
5 JonTheGeek     
6 jakekaupp      
# ℹ 261 more rows
#
# A tibble: 975 × 2
   from    to
  &lt;int&gt; &lt;int&gt;
1     1    32
2     1    36
3     2   120
# ℹ 972 more rows</code></pre>
</div>
</div>
<p>We can see that the network now has 267 individuals, all of which sent more than one interaction. The individuals in a network are often referred to as&nbsp;<em>nodes</em>&nbsp;(and, this terminology is used in the {ggraph} functions for plotting the individuals - the nodes - in a network). We note that nodes are sometimes referred to as&nbsp;<em>vertices</em>&nbsp;or&nbsp;<em>actors</em>; like the different names for edges, these generally mean the same thing.</p>
<p>Next, we’ll use the&nbsp;<code>ggraph()</code>&nbsp;function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="http://localhost:3849/#cb70-1" aria-hidden="true" tabindex="-1"></a>g <span class="sc">%&gt;%</span></span>
<span id="cb70-2"><a href="http://localhost:3849/#cb70-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># we chose the kk layout as it created a graph which was easy-to-interpret, but others are available; see ?ggraph</span></span>
<span id="cb70-3"><a href="http://localhost:3849/#cb70-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggraph</span>(<span class="at">layout =</span> <span class="st">"kk"</span>) <span class="sc">+</span></span>
<span id="cb70-4"><a href="http://localhost:3849/#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># this adds the points to the graph</span></span>
<span id="cb70-5"><a href="http://localhost:3849/#cb70-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_node_point</span>() <span class="sc">+</span></span>
<span id="cb70-6"><a href="http://localhost:3849/#cb70-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># this adds the links, or the edges; alpha = .2 makes it so that the lines are partially transparent</span></span>
<span id="cb70-7"><a href="http://localhost:3849/#cb70-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_edge_link</span>(<span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb70-8"><a href="http://localhost:3849/#cb70-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># this last line of code adds a ggplot2 theme suitable for network graphs</span></span>
<span id="cb70-9"><a href="http://localhost:3849/#cb70-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_graph</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using the `size` aesthetic in this geom was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` in the `default_aes` field and elsewhere instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="./Unit4_RTutorial Week_files/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Finally, let’s size the points based on a measure of centrality. A common way to do this is to measure how influential an individual may be based on the interactions observed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="http://localhost:3849/#cb72-1" aria-hidden="true" tabindex="-1"></a>g <span class="sc">%&gt;%</span> </span>
<span id="cb72-2"><a href="http://localhost:3849/#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># this calculates the centrality of each individual using the built-in centrality_authority() function</span></span>
<span id="cb72-3"><a href="http://localhost:3849/#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">centrality =</span> <span class="fu">centrality_authority</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb72-4"><a href="http://localhost:3849/#cb72-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggraph</span>(<span class="at">layout =</span> <span class="st">"kk"</span>) <span class="sc">+</span> </span>
<span id="cb72-5"><a href="http://localhost:3849/#cb72-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_node_point</span>(<span class="fu">aes</span>(<span class="at">size =</span> centrality, <span class="at">color =</span> centrality)) <span class="sc">+</span></span>
<span id="cb72-6"><a href="http://localhost:3849/#cb72-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># this line colors the points based upon their centrality</span></span>
<span id="cb72-7"><a href="http://localhost:3849/#cb72-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_continuous</span>(<span class="at">guide =</span> <span class="st">'legend'</span>) <span class="sc">+</span> </span>
<span id="cb72-8"><a href="http://localhost:3849/#cb72-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_edge_link</span>(<span class="at">alpha =</span> .<span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="./Unit4_RTutorial Week_files/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="your-turn-8" class="level3">
<h3 class="anchored" data-anchor-id="your-turn-8">Your Turn<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#your-turn-8" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h3>
<p><strong>What this social network graph tells us regarding to the measure of centrality?</strong></p>
<ul>
<li><strong>A large majority of the individuals were interacting with one another, there are a number of users that were significant contributors to the discussion.</strong></li>
<li>I believe that if this network was presented in 3 Dimensions, it would allow us to evaluate the structure more thoroughly. It seems like looking at a tree from a top-down perspective whereas understanding the nuances would require a lateral perspective.</li>
</ul>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3849/#conclusion" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h2>
<p>In this chapter, we used social media data from the #tidytuesday hashtag to prepare and visualize social network data. Sociograms are a useful visualization tool to reveal who is interacting with whom–and, in some cases, to suggest why. In our applications of data science, we have found that the individuals (such as teachers or students) who are represented in a network often like to see what the network (and the relationships in it)&nbsp;<em>look like</em>. It can be compelling to think about why networks are the way they are, and how changes could be made to - for example - foster more connections between individuals who have few opportunities to interact. In this way, social network analysis can be useful to the data scientist in education because it provides a technique to communicate with other educational stakeholders in a compelling way.</p>
<p>Social network analysis is a broad (and growing) domain, and this chapter was intended to present some of its foundation. Fortunately for R users, many recent developments are implemented first in R (e.g.,&nbsp;(<a href="https://datascienceineducation.com/c12#ref-R-amen"><strong>R-amen?</strong></a>)). If you are interested in some of the additional steps that you can take to model and analyze network data, consider the appendix on two types of models (for selection and influence processes),&nbsp;<a href="https://datascienceineducation.com/c20#c20c">Appendix C</a>.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<div class="modal__dialog micromodal-slide" id="quarto-log-error-modal" aria-hidden="true">
  <div class="modal__overlay" tabindex="2" data-micromodal-close="">
    <div class="modal__container" role="dialog" aria-modal="true" aria-labelledby="quarto-log-error-modal-title">
      <header class="modal__header">
        <h2 class="modal__title" id="quarto-log-error-modal-title">
          <i class="bi bi-exclamation-circle"></i>Error
        </h2>
        <button class="modal__close" aria-label="Close modal" data-micromodal-close=""></button>
      </header>
      <div class="modal__content" id="quarto-log-error-modal-content">
        <pre tabindex="1" id="quarto-log-error-display"></pre>
      </div>
      <footer class="modal__footer">
      </footer>
    </div>
  </div>
</div>
<style type="text/css">
#quarto-log-error-modal .modal__overlay {
  z-index: 5000;
}
#quarto-log-error-modal-content {
  border: 1px solid #dee2e6;
  overflow-y: auto;
}
#quarto-log-error-display {
  min-height: 100px;
  padding: 8px;
  margin-bottom: 0;
  font-family: monospace;
}
#quarto-log-error-display:focus {
  outline: none;
}
.modal__dialog {
  font-size: 16px;
}
.modal__overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0,0,0,0.4);
  display: flex;
  justify-content: center;
  align-items: center;
}
.modal__container {
  position: fixed;
  top: 80px;
  background-color: #fff;
  padding: 15px;
  padding-top: 10px;
  min-width: 500px;
  max-width: 90%;
  max-height: 90vh;
  border-radius: 4px;
  overflow-y: auto;
  box-sizing: border-box;
}
.modal__header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.modal__title {
  margin-top: 0;
  margin-bottom: 0;
  font-weight: 600;
  border-bottom: none;
  padding-bottom: 10px;
  font-size: 20px;
  color: rgb(191,71,65);
  line-height: 1.25;
  box-sizing: border-box;
}
.modal__title .bi {
  margin-right: 7px;
}
.modal__close {
  background: transparent;
  border: 0;
  margin-bottom: 10px;
}
.modal__header .modal__close:before { content: "\2715"; }
.modal__content {
  margin-top: 0;
  margin-bottom: 0;
}
@keyframes mmfadeIn {
    from { opacity: 0; }
      to { opacity: 1; }
}
@keyframes mmfadeOut {
    from { opacity: 1; }
      to { opacity: 0; }
}
@keyframes mmslideIn {
  from { transform: translateY(15%); }
    to { transform: translateY(0); }
}
@keyframes mmslideOut {
    from { transform: translateY(0); }
    to { transform: translateY(-10%); }
}
.micromodal-slide {
  display: none;
}
.micromodal-slide.is-open {
  display: block;
}
.micromodal-slide[aria-hidden="false"] .modal__overlay {
  animation: mmfadeIn .3s cubic-bezier(0.0, 0.0, 0.2, 1);
}
.micromodal-slide[aria-hidden="false"] .modal__container {
  animation: mmslideIn .3s cubic-bezier(0, 0, .2, 1);
}
.micromodal-slide[aria-hidden="true"] .modal__overlay {
  animation: mmfadeOut .3s cubic-bezier(0.0, 0.0, 0.2, 1);
}
.micromodal-slide[aria-hidden="true"] .modal__container {
  animation: mmslideOut .3s cubic-bezier(0, 0, .2, 1);
}
.micromodal-slide .modal__container,
.micromodal-slide .modal__overlay {
  will-change: transform;
} 
</style>
<script type="text/javascript">
  window.backupDefine = window.define; window.define = undefined;
  /*  ansi_up.js
   *  author : Dru Nelson
   *  license : MIT
   *  http://github.com/drudru/ansi_up
   */
   (function (root, factory) {
      if (typeof define === 'function' && define.amd) {
          // AMD. Register as an anonymous module.
          define(['exports'], factory);
      } else if (typeof exports === 'object' && typeof exports.nodeName !== 'string') {
          // CommonJS
          factory(exports);
      } else {
          // Browser globals
          var exp = {};
          factory(exp);
          root.AnsiUp = exp.default;
      }
  }(this, function (exports) {
  "use strict";
  var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
      if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
      return cooked;
  };
  var PacketKind;
  (function (PacketKind) {
      PacketKind[PacketKind["EOS"] = 0] = "EOS";
      PacketKind[PacketKind["Text"] = 1] = "Text";
      PacketKind[PacketKind["Incomplete"] = 2] = "Incomplete";
      PacketKind[PacketKind["ESC"] = 3] = "ESC";
      PacketKind[PacketKind["Unknown"] = 4] = "Unknown";
      PacketKind[PacketKind["SGR"] = 5] = "SGR";
      PacketKind[PacketKind["OSCURL"] = 6] = "OSCURL";
  })(PacketKind || (PacketKind = {}));
  var AnsiUp = (function () {
      function AnsiUp() {
          this.VERSION = "5.1.0";
          this.setup_palettes();
          this._use_classes = false;
          this.bold = false;
          this.italic = false;
          this.underline = false;
          this.fg = this.bg = null;
          this._buffer = '';
          this._url_whitelist = { 'http': 1, 'https': 1 };
      }
      Object.defineProperty(AnsiUp.prototype, "use_classes", {
          get: function () {
              return this._use_classes;
          },
          set: function (arg) {
              this._use_classes = arg;
          },
          enumerable: false,
          configurable: true
      });
      Object.defineProperty(AnsiUp.prototype, "url_whitelist", {
          get: function () {
              return this._url_whitelist;
          },
          set: function (arg) {
              this._url_whitelist = arg;
          },
          enumerable: false,
          configurable: true
      });
      AnsiUp.prototype.setup_palettes = function () {
          var _this = this;
          this.ansi_colors =
              [
                  [
                      { rgb: [0, 0, 0], class_name: "ansi-black" },
                      { rgb: [187, 0, 0], class_name: "ansi-red" },
                      { rgb: [0, 187, 0], class_name: "ansi-green" },
                      { rgb: [187, 187, 0], class_name: "ansi-yellow" },
                      { rgb: [0, 0, 187], class_name: "ansi-blue" },
                      { rgb: [187, 0, 187], class_name: "ansi-magenta" },
                      { rgb: [0, 187, 187], class_name: "ansi-cyan" },
                      { rgb: [255, 255, 255], class_name: "ansi-white" }
                  ],
                  [
                      { rgb: [85, 85, 85], class_name: "ansi-bright-black" },
                      { rgb: [255, 85, 85], class_name: "ansi-bright-red" },
                      { rgb: [0, 255, 0], class_name: "ansi-bright-green" },
                      { rgb: [255, 255, 85], class_name: "ansi-bright-yellow" },
                      { rgb: [85, 85, 255], class_name: "ansi-bright-blue" },
                      { rgb: [255, 85, 255], class_name: "ansi-bright-magenta" },
                      { rgb: [85, 255, 255], class_name: "ansi-bright-cyan" },
                      { rgb: [255, 255, 255], class_name: "ansi-bright-white" }
                  ]
              ];
          this.palette_256 = [];
          this.ansi_colors.forEach(function (palette) {
              palette.forEach(function (rec) {
                  _this.palette_256.push(rec);
              });
          });
          var levels = [0, 95, 135, 175, 215, 255];
          for (var r = 0; r < 6; ++r) {
              for (var g = 0; g < 6; ++g) {
                  for (var b = 0; b < 6; ++b) {
                      var col = { rgb: [levels[r], levels[g], levels[b]], class_name: 'truecolor' };
                      this.palette_256.push(col);
                  }
              }
          }
          var grey_level = 8;
          for (var i = 0; i < 24; ++i, grey_level += 10) {
              var gry = { rgb: [grey_level, grey_level, grey_level], class_name: 'truecolor' };
              this.palette_256.push(gry);
          }
      };
      AnsiUp.prototype.escape_txt_for_html = function (txt) {
          return txt.replace(/[&<>"']/gm, function (str) {
              if (str === "&")
                  return "&amp;";
              if (str === "<")
                  return "&lt;";
              if (str === ">")
                  return "&gt;";
              if (str === "\"")
                  return "&quot;";
              if (str === "'")
                  return "&#x27;";
          });
      };
      AnsiUp.prototype.append_buffer = function (txt) {
          var str = this._buffer + txt;
          this._buffer = str;
      };
      AnsiUp.prototype.get_next_packet = function () {
          var pkt = {
              kind: PacketKind.EOS,
              text: '',
              url: ''
          };
          var len = this._buffer.length;
          if (len == 0)
              return pkt;
          var pos = this._buffer.indexOf("\x1B");
          if (pos == -1) {
              pkt.kind = PacketKind.Text;
              pkt.text = this._buffer;
              this._buffer = '';
              return pkt;
          }
          if (pos > 0) {
              pkt.kind = PacketKind.Text;
              pkt.text = this._buffer.slice(0, pos);
              this._buffer = this._buffer.slice(pos);
              return pkt;
          }
          if (pos == 0) {
              if (len == 1) {
                  pkt.kind = PacketKind.Incomplete;
                  return pkt;
              }
              var next_char = this._buffer.charAt(1);
              if ((next_char != '[') && (next_char != ']')) {
                  pkt.kind = PacketKind.ESC;
                  pkt.text = this._buffer.slice(0, 1);
                  this._buffer = this._buffer.slice(1);
                  return pkt;
              }
              if (next_char == '[') {
                  if (!this._csi_regex) {
                      this._csi_regex = rgx(__makeTemplateObject(["\n                        ^                           # beginning of line\n                                                    #\n                                                    # First attempt\n                        (?:                         # legal sequence\n                          \u001B[                      # CSI\n                          ([<-?]?)              # private-mode char\n                          ([d;]*)                    # any digits or semicolons\n                          ([ -/]?               # an intermediate modifier\n                          [@-~])                # the command\n                        )\n                        |                           # alternate (second attempt)\n                        (?:                         # illegal sequence\n                          \u001B[                      # CSI\n                          [ -~]*                # anything legal\n                          ([\0-\u001F:])              # anything illegal\n                        )\n                    "], ["\n                        ^                           # beginning of line\n                                                    #\n                                                    # First attempt\n                        (?:                         # legal sequence\n                          \\x1b\\[                      # CSI\n                          ([\\x3c-\\x3f]?)              # private-mode char\n                          ([\\d;]*)                    # any digits or semicolons\n                          ([\\x20-\\x2f]?               # an intermediate modifier\n                          [\\x40-\\x7e])                # the command\n                        )\n                        |                           # alternate (second attempt)\n                        (?:                         # illegal sequence\n                          \\x1b\\[                      # CSI\n                          [\\x20-\\x7e]*                # anything legal\n                          ([\\x00-\\x1f:])              # anything illegal\n                        )\n                    "]));
                  }
                  var match = this._buffer.match(this._csi_regex);
                  if (match === null) {
                      pkt.kind = PacketKind.Incomplete;
                      return pkt;
                  }
                  if (match[4]) {
                      pkt.kind = PacketKind.ESC;
                      pkt.text = this._buffer.slice(0, 1);
                      this._buffer = this._buffer.slice(1);
                      return pkt;
                  }
                  if ((match[1] != '') || (match[3] != 'm'))
                      pkt.kind = PacketKind.Unknown;
                  else
                      pkt.kind = PacketKind.SGR;
                  pkt.text = match[2];
                  var rpos = match[0].length;
                  this._buffer = this._buffer.slice(rpos);
                  return pkt;
              }
              if (next_char == ']') {
                  if (len < 4) {
                      pkt.kind = PacketKind.Incomplete;
                      return pkt;
                  }
                  if ((this._buffer.charAt(2) != '8')
                      || (this._buffer.charAt(3) != ';')) {
                      pkt.kind = PacketKind.ESC;
                      pkt.text = this._buffer.slice(0, 1);
                      this._buffer = this._buffer.slice(1);
                      return pkt;
                  }
                  if (!this._osc_st) {
                      this._osc_st = rgxG(__makeTemplateObject(["\n                        (?:                         # legal sequence\n                          (\u001B\\)                    # ESC                           |                           # alternate\n                          (\u0007)                      # BEL (what xterm did)\n                        )\n                        |                           # alternate (second attempt)\n                        (                           # illegal sequence\n                          [\0-\u0006]                 # anything illegal\n                          |                           # alternate\n                          [\b-\u001A]                 # anything illegal\n                          |                           # alternate\n                          [\u001C-\u001F]                 # anything illegal\n                        )\n                    "], ["\n                        (?:                         # legal sequence\n                          (\\x1b\\\\)                    # ESC \\\n                          |                           # alternate\n                          (\\x07)                      # BEL (what xterm did)\n                        )\n                        |                           # alternate (second attempt)\n                        (                           # illegal sequence\n                          [\\x00-\\x06]                 # anything illegal\n                          |                           # alternate\n                          [\\x08-\\x1a]                 # anything illegal\n                          |                           # alternate\n                          [\\x1c-\\x1f]                 # anything illegal\n                        )\n                    "]));
                  }
                  this._osc_st.lastIndex = 0;
                  {
                      var match_1 = this._osc_st.exec(this._buffer);
                      if (match_1 === null) {
                          pkt.kind = PacketKind.Incomplete;
                          return pkt;
                      }
                      if (match_1[3]) {
                          pkt.kind = PacketKind.ESC;
                          pkt.text = this._buffer.slice(0, 1);
                          this._buffer = this._buffer.slice(1);
                          return pkt;
                      }
                  }
                  {
                      var match_2 = this._osc_st.exec(this._buffer);
                      if (match_2 === null) {
                          pkt.kind = PacketKind.Incomplete;
                          return pkt;
                      }
                      if (match_2[3]) {
                          pkt.kind = PacketKind.ESC;
                          pkt.text = this._buffer.slice(0, 1);
                          this._buffer = this._buffer.slice(1);
                          return pkt;
                      }
                  }
                  if (!this._osc_regex) {
                      this._osc_regex = rgx(__makeTemplateObject(["\n                        ^                           # beginning of line\n                                                    #\n                        \u001B]8;                    # OSC Hyperlink\n                        [ -:<-~]*       # params (excluding ;)\n                        ;                           # end of params\n                        ([!-~]{0,512})        # URL capture\n                        (?:                         # ST\n                          (?:\u001B\\)                  # ESC                           |                           # alternate\n                          (?:\u0007)                    # BEL (what xterm did)\n                        )\n                        ([ -~]+)              # TEXT capture\n                        \u001B]8;;                   # OSC Hyperlink End\n                        (?:                         # ST\n                          (?:\u001B\\)                  # ESC                           |                           # alternate\n                          (?:\u0007)                    # BEL (what xterm did)\n                        )\n                    "], ["\n                        ^                           # beginning of line\n                                                    #\n                        \\x1b\\]8;                    # OSC Hyperlink\n                        [\\x20-\\x3a\\x3c-\\x7e]*       # params (excluding ;)\n                        ;                           # end of params\n                        ([\\x21-\\x7e]{0,512})        # URL capture\n                        (?:                         # ST\n                          (?:\\x1b\\\\)                  # ESC \\\n                          |                           # alternate\n                          (?:\\x07)                    # BEL (what xterm did)\n                        )\n                        ([\\x20-\\x7e]+)              # TEXT capture\n                        \\x1b\\]8;;                   # OSC Hyperlink End\n                        (?:                         # ST\n                          (?:\\x1b\\\\)                  # ESC \\\n                          |                           # alternate\n                          (?:\\x07)                    # BEL (what xterm did)\n                        )\n                    "]));
                  }
                  var match = this._buffer.match(this._osc_regex);
                  if (match === null) {
                      pkt.kind = PacketKind.ESC;
                      pkt.text = this._buffer.slice(0, 1);
                      this._buffer = this._buffer.slice(1);
                      return pkt;
                  }
                  pkt.kind = PacketKind.OSCURL;
                  pkt.url = match[1];
                  pkt.text = match[2];
                  var rpos = match[0].length;
                  this._buffer = this._buffer.slice(rpos);
                  return pkt;
              }
          }
      };
      AnsiUp.prototype.ansi_to_html = function (txt) {
          this.append_buffer(txt);
          var blocks = [];
          while (true) {
              var packet = this.get_next_packet();
              if ((packet.kind == PacketKind.EOS)
                  || (packet.kind == PacketKind.Incomplete))
                  break;
              if ((packet.kind == PacketKind.ESC)
                  || (packet.kind == PacketKind.Unknown))
                  continue;
              if (packet.kind == PacketKind.Text)
                  blocks.push(this.transform_to_html(this.with_state(packet)));
              else if (packet.kind == PacketKind.SGR)
                  this.process_ansi(packet);
              else if (packet.kind == PacketKind.OSCURL)
                  blocks.push(this.process_hyperlink(packet));
          }
          return blocks.join("");
      };
      AnsiUp.prototype.with_state = function (pkt) {
          return { bold: this.bold, italic: this.italic, underline: this.underline, fg: this.fg, bg: this.bg, text: pkt.text };
      };
      AnsiUp.prototype.process_ansi = function (pkt) {
          var sgr_cmds = pkt.text.split(';');
          while (sgr_cmds.length > 0) {
              var sgr_cmd_str = sgr_cmds.shift();
              var num = parseInt(sgr_cmd_str, 10);
              if (isNaN(num) || num === 0) {
                  this.fg = this.bg = null;
                  this.bold = false;
                  this.italic = false;
                  this.underline = false;
              }
              else if (num === 1) {
                  this.bold = true;
              }
              else if (num === 3) {
                  this.italic = true;
              }
              else if (num === 4) {
                  this.underline = true;
              }
              else if (num === 22) {
                  this.bold = false;
              }
              else if (num === 23) {
                  this.italic = false;
              }
              else if (num === 24) {
                  this.underline = false;
              }
              else if (num === 39) {
                  this.fg = null;
              }
              else if (num === 49) {
                  this.bg = null;
              }
              else if ((num >= 30) && (num < 38)) {
                  this.fg = this.ansi_colors[0][(num - 30)];
              }
              else if ((num >= 40) && (num < 48)) {
                  this.bg = this.ansi_colors[0][(num - 40)];
              }
              else if ((num >= 90) && (num < 98)) {
                  this.fg = this.ansi_colors[1][(num - 90)];
              }
              else if ((num >= 100) && (num < 108)) {
                  this.bg = this.ansi_colors[1][(num - 100)];
              }
              else if (num === 38 || num === 48) {
                  if (sgr_cmds.length > 0) {
                      var is_foreground = (num === 38);
                      var mode_cmd = sgr_cmds.shift();
                      if (mode_cmd === '5' && sgr_cmds.length > 0) {
                          var palette_index = parseInt(sgr_cmds.shift(), 10);
                          if (palette_index >= 0 && palette_index <= 255) {
                              if (is_foreground)
                                  this.fg = this.palette_256[palette_index];
                              else
                                  this.bg = this.palette_256[palette_index];
                          }
                      }
                      if (mode_cmd === '2' && sgr_cmds.length > 2) {
                          var r = parseInt(sgr_cmds.shift(), 10);
                          var g = parseInt(sgr_cmds.shift(), 10);
                          var b = parseInt(sgr_cmds.shift(), 10);
                          if ((r >= 0 && r <= 255) && (g >= 0 && g <= 255) && (b >= 0 && b <= 255)) {
                              var c = { rgb: [r, g, b], class_name: 'truecolor' };
                              if (is_foreground)
                                  this.fg = c;
                              else
                                  this.bg = c;
                          }
                      }
                  }
              }
          }
      };
      AnsiUp.prototype.transform_to_html = function (fragment) {
          var txt = fragment.text;
          if (txt.length === 0)
              return txt;
          txt = this.escape_txt_for_html(txt);
          if (!fragment.bold && !fragment.italic && !fragment.underline && fragment.fg === null && fragment.bg === null)
              return txt;
          var styles = [];
          var classes = [];
          var fg = fragment.fg;
          var bg = fragment.bg;
          if (fragment.bold)
              styles.push('font-weight:bold');
          if (fragment.italic)
              styles.push('font-style:italic');
          if (fragment.underline)
              styles.push('text-decoration:underline');
          if (!this._use_classes) {
              if (fg)
                  styles.push("color:rgb(" + fg.rgb.join(',') + ")");
              if (bg)
                  styles.push("background-color:rgb(" + bg.rgb + ")");
          }
          else {
              if (fg) {
                  if (fg.class_name !== 'truecolor') {
                      classes.push(fg.class_name + "-fg");
                  }
                  else {
                      styles.push("color:rgb(" + fg.rgb.join(',') + ")");
                  }
              }
              if (bg) {
                  if (bg.class_name !== 'truecolor') {
                      classes.push(bg.class_name + "-bg");
                  }
                  else {
                      styles.push("background-color:rgb(" + bg.rgb.join(',') + ")");
                  }
              }
          }
          var class_string = '';
          var style_string = '';
          if (classes.length)
              class_string = " class=\"" + classes.join(' ') + "\"";
          if (styles.length)
              style_string = " style=\"" + styles.join(';') + "\"";
          return "<span" + style_string + class_string + ">" + txt + "</span>";
      };
      ;
      AnsiUp.prototype.process_hyperlink = function (pkt) {
          var parts = pkt.url.split(':');
          if (parts.length < 1)
              return '';
          if (!this._url_whitelist[parts[0]])
              return '';
          var result = "<a href=\"" + this.escape_txt_for_html(pkt.url) + "\">" + this.escape_txt_for_html(pkt.text) + "</a>";
          return result;
      };
      return AnsiUp;
  }());
  function rgx(tmplObj) {
      var subst = [];
      for (var _i = 1; _i < arguments.length; _i++) {
          subst[_i - 1] = arguments[_i];
      }
      var regexText = tmplObj.raw[0];
      var wsrgx = /^\s+|\s+\n|\s*#[\s\S]*?\n|\n/gm;
      var txt2 = regexText.replace(wsrgx, '');
      return new RegExp(txt2);
  }
  function rgxG(tmplObj) {
      var subst = [];
      for (var _i = 1; _i < arguments.length; _i++) {
          subst[_i - 1] = arguments[_i];
      }
      var regexText = tmplObj.raw[0];
      var wsrgx = /^\s+|\s+\n|\s*#[\s\S]*?\n|\n/gm;
      var txt2 = regexText.replace(wsrgx, '');
      return new RegExp(txt2, 'g');
  }
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.default = AnsiUp;
  }));
  // micromodal: https://github.com/Ghosh/micromodal
  !function(e,t){"object"==typeof exports&&"undefined"!=typeof module?module.exports=t():"function"==typeof define&&define.amd?define(t):(e="undefined"!=typeof globalThis?globalThis:e||self).MicroModal=t()}(this,(function(){"use strict";function e(e,t){for(var o=0;o<t.length;o++){var n=t[o];n.enumerable=n.enumerable||!1,n.configurable=!0,"value"in n&&(n.writable=!0),Object.defineProperty(e,n.key,n)}}function t(e){return function(e){if(Array.isArray(e))return o(e)}(e)||function(e){if("undefined"!=typeof Symbol&&Symbol.iterator in Object(e))return Array.from(e)}(e)||function(e,t){if(!e)return;if("string"==typeof e)return o(e,t);var n=Object.prototype.toString.call(e).slice(8,-1);"Object"===n&&e.constructor&&(n=e.constructor.name);if("Map"===n||"Set"===n)return Array.from(e);if("Arguments"===n||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n))return o(e,t)}(e)||function(){throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}()}function o(e,t){(null==t||t>e.length)&&(t=e.length);for(var o=0,n=new Array(t);o<t;o++)n[o]=e[o];return n}var n,i,a,r,s,l=(n=["a[href]","area[href]",'input:not([disabled]):not([type="hidden"]):not([aria-hidden])',"select:not([disabled]):not([aria-hidden])","textarea:not([disabled]):not([aria-hidden])","button:not([disabled]):not([aria-hidden])","iframe","object","embed","[contenteditable]",'[tabindex]:not([tabindex^="-"])'],i=function(){function o(e){var n=e.targetModal,i=e.triggers,a=void 0===i?[]:i,r=e.onShow,s=void 0===r?function(){}:r,l=e.onClose,c=void 0===l?function(){}:l,d=e.openTrigger,u=void 0===d?"data-micromodal-trigger":d,f=e.closeTrigger,h=void 0===f?"data-micromodal-close":f,v=e.openClass,g=void 0===v?"is-open":v,m=e.disableScroll,b=void 0!==m&&m,y=e.disableFocus,p=void 0!==y&&y,w=e.awaitCloseAnimation,E=void 0!==w&&w,k=e.awaitOpenAnimation,M=void 0!==k&&k,A=e.debugMode,C=void 0!==A&&A;!function(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}(this,o),this.modal=document.getElementById(n),this.config={debugMode:C,disableScroll:b,openTrigger:u,closeTrigger:h,openClass:g,onShow:s,onClose:c,awaitCloseAnimation:E,awaitOpenAnimation:M,disableFocus:p},a.length>0&&this.registerTriggers.apply(this,t(a)),this.onClick=this.onClick.bind(this),this.onKeydown=this.onKeydown.bind(this)}var i,a,r;return i=o,(a=[{key:"registerTriggers",value:function(){for(var e=this,t=arguments.length,o=new Array(t),n=0;n<t;n++)o[n]=arguments[n];o.filter(Boolean).forEach((function(t){t.addEventListener("click",(function(t){return e.showModal(t)}))}))}},{key:"showModal",value:function(){var e=this,t=arguments.length>0&&void 0!==arguments[0]?arguments[0]:null;if(this.activeElement=document.activeElement,this.modal.setAttribute("aria-hidden","false"),this.modal.classList.add(this.config.openClass),this.scrollBehaviour("disable"),this.addEventListeners(),this.config.awaitOpenAnimation){var o=function t(){e.modal.removeEventListener("animationend",t,!1),e.setFocusToFirstNode()};this.modal.addEventListener("animationend",o,!1)}else this.setFocusToFirstNode();this.config.onShow(this.modal,this.activeElement,t)}},{key:"closeModal",value:function(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:null,t=this.modal;if(this.modal.setAttribute("aria-hidden","true"),this.removeEventListeners(),this.scrollBehaviour("enable"),this.activeElement&&this.activeElement.focus&&this.activeElement.focus(),this.config.onClose(this.modal,this.activeElement,e),this.config.awaitCloseAnimation){var o=this.config.openClass;this.modal.addEventListener("animationend",(function e(){t.classList.remove(o),t.removeEventListener("animationend",e,!1)}),!1)}else t.classList.remove(this.config.openClass)}},{key:"closeModalById",value:function(e){this.modal=document.getElementById(e),this.modal&&this.closeModal()}},{key:"scrollBehaviour",value:function(e){if(this.config.disableScroll){var t=document.querySelector("body");switch(e){case"enable":Object.assign(t.style,{overflow:""});break;case"disable":Object.assign(t.style,{overflow:"hidden"})}}}},{key:"addEventListeners",value:function(){this.modal.addEventListener("touchstart",this.onClick),this.modal.addEventListener("click",this.onClick),document.addEventListener("keydown",this.onKeydown)}},{key:"removeEventListeners",value:function(){this.modal.removeEventListener("touchstart",this.onClick),this.modal.removeEventListener("click",this.onClick),document.removeEventListener("keydown",this.onKeydown)}},{key:"onClick",value:function(e){(e.target.hasAttribute(this.config.closeTrigger)||e.target.parentNode.hasAttribute(this.config.closeTrigger))&&(e.preventDefault(),e.stopPropagation(),this.closeModal(e))}},{key:"onKeydown",value:function(e){27===e.keyCode&&this.closeModal(e),9===e.keyCode&&this.retainFocus(e)}},{key:"getFocusableNodes",value:function(){var e=this.modal.querySelectorAll(n);return Array.apply(void 0,t(e))}},{key:"setFocusToFirstNode",value:function(){var e=this;if(!this.config.disableFocus){var t=this.getFocusableNodes();if(0!==t.length){var o=t.filter((function(t){return!t.hasAttribute(e.config.closeTrigger)}));o.length>0&&o[0].focus(),0===o.length&&t[0].focus()}}}},{key:"retainFocus",value:function(e){var t=this.getFocusableNodes();if(0!==t.length)if(t=t.filter((function(e){return null!==e.offsetParent})),this.modal.contains(document.activeElement)){var o=t.indexOf(document.activeElement);e.shiftKey&&0===o&&(t[t.length-1].focus(),e.preventDefault()),!e.shiftKey&&t.length>0&&o===t.length-1&&(t[0].focus(),e.preventDefault())}else t[0].focus()}}])&&e(i.prototype,a),r&&e(i,r),o}(),a=null,r=function(e){if(!document.getElementById(e))return console.warn("MicroModal: ❗Seems like you have missed %c'".concat(e,"'"),"background-color: #f8f9fa;color: #50596c;font-weight: bold;","ID somewhere in your code. Refer example below to resolve it."),console.warn("%cExample:","background-color: #f8f9fa;color: #50596c;font-weight: bold;",'<div class="modal" id="'.concat(e,'"></div>')),!1},s=function(e,t){if(function(e){e.length<=0&&(console.warn("MicroModal: ❗Please specify at least one %c'micromodal-trigger'","background-color: #f8f9fa;color: #50596c;font-weight: bold;","data attribute."),console.warn("%cExample:","background-color: #f8f9fa;color: #50596c;font-weight: bold;",'<a href="#" data-micromodal-trigger="my-modal"></a>'))}(e),!t)return!0;for(var o in t)r(o);return!0},{init:function(e){var o=Object.assign({},{openTrigger:"data-micromodal-trigger"},e),n=t(document.querySelectorAll("[".concat(o.openTrigger,"]"))),r=function(e,t){var o=[];return e.forEach((function(e){var n=e.attributes[t].value;void 0===o[n]&&(o[n]=[]),o[n].push(e)})),o}(n,o.openTrigger);if(!0!==o.debugMode||!1!==s(n,r))for(var l in r){var c=r[l];o.targetModal=l,o.triggers=t(c),a=new i(o)}},show:function(e,t){var o=t||{};o.targetModal=e,!0===o.debugMode&&!1===r(e)||(a&&a.removeEventListeners(),(a=new i(o)).showModal())},close:function(e){e?a.closeModalById(e):a.closeModal()}});return"undefined"!=typeof window&&(window.MicroModal=l),l}));  
  window.define = window.backupDefine; window.backupDefine = undefined;
  </script>
<script type="text/javascript">
  (function () {
    // forward keydown events so shortcuts can work in vscode, see:
    // https://github.com/microsoft/vscode/issues/65452#issuecomment-586485815
    if (window.parent.postMessage) {
      window.document.addEventListener('keydown', e => {
        const event = {
          type: "keydown",
          data: {
            altKey: e.altKey,
            code: e.code,
            ctrlKey: e.ctrlKey,
            isComposing: e.isComposing,
            key: e.key,
            location: e.location,
            metaKey: e.metaKey,
            repeat: e.repeat,
            shiftKey: e.shiftKey
          }
        };
        window.parent.postMessage(event, '*');
      });
    }
    // listen for execCommand messages
    window.addEventListener("message", function (event) {
      if (event.data.type === "devhost-exec-command") {
        window.document.execCommand(event.data.data);
      } 
    }, true);
    const logEntries = new Array(1000);
    logEntries.offset = 0;
    function recordLogEntry(entry) {
      logEntries[logEntries.offset++] = entry;
      logEntries.offset %= logEntries.length;
    }
    function getLogEntry(i) { // backwards, 0 is most recent
        return logEntries[(logEntries.offset - 1 - i + logEntries.length) % logEntries.length];
    }
    const protocol = window.location.protocol === "https:" ? "wss:" : "ws:";
    let path = window.location.pathname;
    if (!/\/$/.test(path)) path += "/";
    const devServerSocket = new WebSocket(protocol + "//" + window.location.host + path);
    let reloadPage = true;
    addEventListener("beforeunload", () => {
      // don't reload page in case of navigation events
      reloadPage = false;
    })
    devServerSocket.onopen = () => {
      console.log('Socket connection open. Listening for events.');
      // if the socket closes for any reason (e.g. this occurs in electron apps
      // when the computer suspends) then reload to reestablish the connection 
      devServerSocket.onclose = () => {
        if (reloadPage) {
          console.log('Socket connection closed. Reloading.');
          window.location.reload(true);
        }
      }
    };
    // append for errors that occur within the error window
    let lastError = 0;
    const kErrorWindow = 2500;
    function showError(msg) {
      const ansiUp = new AnsiUp
      const html = ansiUp.ansi_to_html(msg.trim());
      const display = document.getElementById("quarto-log-error-display");
      if (display.innerHTML && ((Date.now() - lastError) < kErrorWindow)) {
        display.innerHTML = display.innerHTML + "<br/>" +  html;
      } else {
        display.innerHTML = html
      }
      lastError = Date.now()
      MicroModal.show('quarto-log-error-modal', {
        awaitCloseAnimation: true,
        onClose: () => { display.innerHTML = ""; }
      });
      // post message to parent indicating we had an error
      if (window.parent.postMessage) {
        window.parent.postMessage({
          type: "error",
          msg: msg,
        }, "*");
      }
    }
    // see if there is already an error to show
    const renderError = document.getElementById("quarto-render-error");
    if (renderError) {
      showError(renderError.innerHTML.trim());
    }
    const normalizeTarget = (target) => {
      return target.replace(/\/index\.html/, "/")
    };
    devServerSocket.onmessage = (msg) => {
      if (msg.data.startsWith('reload')) {
        let target = normalizeTarget(msg.data.replace(/^reload/, ""));
        // prepend proxy path to target if we have one
        if (target) {
          const pathPrefix = 
            window.location.pathname.match(/^.*?\/p\/\w+\//) ||
            window.location.pathname.match(/^.*?\/user\/[\w\d]+\/proxy\/\d+\//);
          if (pathPrefix) {
            target = pathPrefix + target.slice(1);
          }
        }
        if (target && (target !== normalizeTarget(window.location.pathname))) {
          window.location.replace(target);
        } else {
          window.location.reload(true);
        }
      } else if (msg.data.startsWith('log:')) {
        const ansiUp = new AnsiUp
        const log = JSON.parse(msg.data.substr(4));
        recordLogEntry(log);
        if (log.levelName === "ERROR") {
          showError(log.msgFormatted)
        } else {
          // see if there is a knitr error to report
          const kExecutionHalted = "Execution halted";
          if (log.msg.indexOf(kExecutionHalted) !== -1) {
            // scan backwards for beginning of error
            const errorEntries = [getLogEntry(0).msgFormatted];
            for (let i=1; i<logEntries.length; i++) {
              const logEntry = getLogEntry(i);
              if (logEntry) {
                errorEntries.unshift(logEntry.msgFormatted);
                if (logEntry.msg.indexOf("Quitting from lines") !== -1) {
                  showError(errorEntries.join(""));
                  break;
                } else if (logEntry.msg.indexOf(kExecutionHalted) !== -1) {
                  break;
                }
              } else {
                break;
              }
            }
          }
        }
      }
    };
  })();
</script>

<script type="text/javascript">
  if (window.parent.postMessage) {
    // wait for message providing confirmation we are in a devhost
    window.addEventListener("message", function (event) {
      if (event.data.type === "devhost-init") {
        window.quartoDevhost = {
          openInputFile: function (line, column, highlight) {
            window.parent.postMessage({
              type: "openfile",
              file: "C:\Users\thead\AppData\Local\Temp\Rar$DIa22568.32651\Unit4_Rtutorial.qmd",
              line: line,
              column: column,
              highlight: highlight
            }, event.origin);
          }
        };
      } else if (event.data.type === "goback") {
        window.history.back()
      } else if (event.data.type === "goforward") {
        window.history.forward()
      }
    }, true);
    // notify host of navigation (e.g. for 'pop out' command)
    window.parent.postMessage({
      type: "navigate",
      href: window.location.href,
      file: "C:\Users\thead\AppData\Local\Temp\Rar$DIa22568.32651\Unit4_Rtutorial.qmd"
    }, "*");
  }
</script>
</body></html>